/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.alergias;
import clases.doctor;
import clases.enfermedades;
import clases.enfermera;
import clases.medicamentos;
import clases.paciente;
import clases.validaciones;
import conexion_bada.Insert;
import conexion_bada.Insert_doctor;
import conexion_bada.Insert_medicamento;
import conexion_bada.Insert_tratamiento;
import conexion_bada.insert_tratamiento_medicamento;
import java.awt.Color;
import static java.awt.Frame.ICONIFIED;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class agregar_tratamiento extends javax.swing.JFrame {

    Insert_tratamiento mi_trata = new Insert_tratamiento();
    insert_tratamiento_medicamento inserTrataMedi = new insert_tratamiento_medicamento();
    Insert inser = new Insert();
    Insert_doctor inser_doctor = new Insert_doctor();
    Insert_medicamento inserMedicamento = new Insert_medicamento();
    DefaultListModel modeloListMedicamento;
    ArrayList<medicamentos> Listamedicamentos = new ArrayList<>();

    public agregar_tratamiento() {
        initComponents();
        LLenarComboBoxMedicamentos();
        cargarcod();
    }

    public void cargarcod() {
        text_codigo_tratamiento.setEnabled(false);
        text_codigo_tratamiento.setText(String.valueOf(mi_trata.cargarcodigo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargarPaciente = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaPaciente = new javax.swing.JTable();
        BtBuscarPaciente = new javax.swing.JButton();
        text_buscarPacienteDialog = new javax.swing.JTextField();
        cargarP = new javax.swing.JButton();
        cargarDoctor = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaDoctor = new javax.swing.JTable();
        BtBuscarDialogDoctor = new javax.swing.JButton();
        text_buscarDialogDoctor = new javax.swing.JTextField();
        cargarP1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_codigo_paciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_cedula_paciente = new javax.swing.JTextField();
        txt_nombre_paciente = new javax.swing.JTextField();
        txt_apellido_paciente = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        text_codigo_tratamiento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fecha_inicio_medicamento = new com.toedter.calendar.JDateChooser();
        fecha_final_medicamento = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_diagnositico = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        boton_regresar_acceso_doctor = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        JListMedicamentos = new javax.swing.JList<>();
        ComboMedicamentos = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        text_dosis = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        nomb_doctor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        text_budcar_doctor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        apellido_doct = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        especialidad_doctor = new javax.swing.JTextField();
        buscar_doctor = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        cargarPaciente.setResizable(false);

        TablaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "CEDULA", "NOMBRES", "APELLIDOS"
            }
        ));
        TablaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaPacienteMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(TablaPaciente);

        BtBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        BtBuscarPaciente.setToolTipText("BUSCAR PACIENTE");
        BtBuscarPaciente.setBorder(null);
        BtBuscarPaciente.setOpaque(false);
        BtBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarPacienteActionPerformed(evt);
            }
        });

        text_buscarPacienteDialog.setText("Buscar...");
        text_buscarPacienteDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_buscarPacienteDialogMousePressed(evt);
            }
        });
        text_buscarPacienteDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_buscarPacienteDialogActionPerformed(evt);
            }
        });

        cargarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carga-de-archivos.png"))); // NOI18N
        cargarP.setToolTipText("CARGAR CODIGO");
        cargarP.setBorder(null);
        cargarP.setOpaque(false);
        cargarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cargarPacienteLayout = new javax.swing.GroupLayout(cargarPaciente.getContentPane());
        cargarPaciente.getContentPane().setLayout(cargarPacienteLayout);
        cargarPacienteLayout.setHorizontalGroup(
            cargarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cargarPacienteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(text_buscarPacienteDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cargarP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(cargarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cargarPacienteLayout.setVerticalGroup(
            cargarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargarPacienteLayout.createSequentialGroup()
                .addGroup(cargarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cargarPacienteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(text_buscarPacienteDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargarPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtBuscarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargarPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cargarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cargarDoctor.setResizable(false);

        TablaDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "CEDULA", "NOMBRES", "APELLIDOS", "ESPECIALIDAD"
            }
        ));
        TablaDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaDoctorMousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(TablaDoctor);

        BtBuscarDialogDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        BtBuscarDialogDoctor.setToolTipText("BUSCAR PACIENTE");
        BtBuscarDialogDoctor.setBorder(null);
        BtBuscarDialogDoctor.setOpaque(false);
        BtBuscarDialogDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarDialogDoctorActionPerformed(evt);
            }
        });

        text_buscarDialogDoctor.setText("Buscar...");
        text_buscarDialogDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_buscarDialogDoctorMousePressed(evt);
            }
        });
        text_buscarDialogDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_buscarDialogDoctorActionPerformed(evt);
            }
        });

        cargarP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carga-de-archivos.png"))); // NOI18N
        cargarP1.setToolTipText("CARGAR CODIGO");
        cargarP1.setBorder(null);
        cargarP1.setOpaque(false);
        cargarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cargarDoctorLayout = new javax.swing.GroupLayout(cargarDoctor.getContentPane());
        cargarDoctor.getContentPane().setLayout(cargarDoctorLayout);
        cargarDoctorLayout.setHorizontalGroup(
            cargarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cargarDoctorLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(cargarDoctorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(text_buscarDialogDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtBuscarDialogDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cargarP1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        cargarDoctorLayout.setVerticalGroup(
            cargarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargarDoctorLayout.createSequentialGroup()
                .addGroup(cargarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cargarDoctorLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(text_buscarDialogDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargarDoctorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtBuscarDialogDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargarDoctorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cargarP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(138, 252, 202));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Tratamiento");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Codigo Paciente:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Datos del Paciente");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Nombres:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Apellidos:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Cedula:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Diagnostico:");

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        buscar.setToolTipText("buscar paciente");
        buscar.setBorder(null);
        buscar.setOpaque(false);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Codigo de Tratamiento:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Datos del Doctor");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Medicamento:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Fecha Inicio:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Fecha Finalización:");

        text_diagnositico.setColumns(20);
        text_diagnositico.setRows(5);
        jScrollPane1.setViewportView(text_diagnositico);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salvar (1).png"))); // NOI18N
        jButton3.setToolTipText("guardar");
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        boton_regresar_acceso_doctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        boton_regresar_acceso_doctor.setToolTipText("regresar");
        boton_regresar_acceso_doctor.setBorder(null);
        boton_regresar_acceso_doctor.setOpaque(false);
        boton_regresar_acceso_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_regresar_acceso_doctorActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jScrollPane2.setViewportView(JListMedicamentos);

        ComboMedicamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un medicamento" }));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/medicamentos.png"))); // NOI18N
        jButton2.setToolTipText("Cargar Medicamento");
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Instrucciones:");

        text_dosis.setColumns(20);
        text_dosis.setRows(5);
        jScrollPane3.setViewportView(text_dosis);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Nombre:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Cedula:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Apellido:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Especialidad:");

        buscar_doctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        buscar_doctor.setToolTipText("BUSCAR DOCTOR");
        buscar_doctor.setBorder(null);
        buscar_doctor.setOpaque(false);
        buscar_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_doctorActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar Medicamento");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Datos de Tratamiento");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_nombre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(text_codigo_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_apellido_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(28, 28, 28)
                                        .addComponent(txt_cedula_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buscar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(text_budcar_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buscar_doctor))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nomb_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellido_doct, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(especialidad_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(209, 209, 209)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(text_codigo_tratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ComboMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addGap(32, 32, 32))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Eliminar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jButton3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(fecha_inicio_medicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fecha_final_medicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(boton_regresar_acceso_doctor)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(boton_regresar_acceso_doctor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(text_codigo_tratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(text_codigo_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_cedula_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buscar))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_nombre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_apellido_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(text_budcar_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(especialidad_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(buscar_doctor))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(nomb_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(apellido_doct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_inicio_medicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_final_medicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(ComboMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jButton2)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(Eliminar)))))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cargarTablaE() {
        DefaultTableModel tb = (DefaultTableModel) TablaDoctor.getModel();
        tb.setNumRows(0);
        List<doctor> com = inser_doctor.ListaDoctor();
        com.stream().forEach(p -> {
            String[] cami = {String.valueOf(p.getCodigo()), p.getCedula(), p.getPri_nomb() + "  " + p.getSeg_nombre(), p.getPrim_apell() + "  " + p.getSeg_apelli()};
            tb.addRow(cami);
        });
    }

    public void buscardoctor() {
        String cedula = text_buscarDialogDoctor.getText();
        var doctorDialogfiltro = new ArrayList<doctor>();
        inser_doctor.ListaDoctor().forEach((e) -> {
            if (e.getCedula().equals(cedula)) {
                doctorDialogfiltro.add(e);
            }
        });
        if (doctorDialogfiltro.size() != 0) {

            String matriz[][] = new String[doctorDialogfiltro.size()][14];
            for (int j = 0; j < doctorDialogfiltro.size(); j++) {
                matriz[j][0] = String.valueOf(doctorDialogfiltro.get(j).getCodigo());
                matriz[j][1] = doctorDialogfiltro.get(j).getCedula();
                matriz[j][2] = doctorDialogfiltro.get(j).getPri_nomb() + "  " + doctorDialogfiltro.get(j).getSeg_nombre();
                matriz[j][3] = doctorDialogfiltro.get(j).getPrim_apell() + "  " + doctorDialogfiltro.get(j).getSeg_apelli();
                matriz[j][4] = doctorDialogfiltro.get(j).getEspecialidad();
            }
            TablaDoctor.setModel(new javax.swing.table.DefaultTableModel(
                    matriz,
                    new String[]{
                        "CODIGO", "CEDULA", "NOMBRES", "APELLIDOS", "ESPECIALIDAD"
                    }
            ));
        } else {
            JOptionPane.showMessageDialog(this, "El doctor no se encuentra registrado");
        }

    }

    public void buscar_paciente() {
        String cedula = text_buscarPacienteDialog.getText();
        var pacienteDialogfiltro = new ArrayList<paciente>();
        inser.ListaPaciente().forEach((e) -> {
            if (e.getCedula().equals(cedula)) {
                pacienteDialogfiltro.add(e);
            }
        });
        if (pacienteDialogfiltro.size() != 0) {

            String matriz[][] = new String[pacienteDialogfiltro.size()][14];
            for (int j = 0; j < pacienteDialogfiltro.size(); j++) {
                matriz[j][0] = String.valueOf(pacienteDialogfiltro.get(j).getCodigo());
                matriz[j][1] = pacienteDialogfiltro.get(j).getCedula();
                matriz[j][2] = pacienteDialogfiltro.get(j).getPri_nomb() + "  " + pacienteDialogfiltro.get(j).getSeg_nombre();
                matriz[j][3] = pacienteDialogfiltro.get(j).getPrim_apell() + "  " + pacienteDialogfiltro.get(j).getSeg_apelli();
                
                
            }
            TablaDoctor.setModel(new javax.swing.table.DefaultTableModel(
                    matriz,
                    new String[]{
                        "CODIGO", "CEDULA", "NOMBRES", "APELLIDOS"
                    }
            ));
        } else {
            JOptionPane.showMessageDialog(this, "El paciente no se encuentra registrado");
        }

    }
    private void TablaPacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPacienteMousePressed

    }//GEN-LAST:event_TablaPacienteMousePressed
    public boolean validaciones() {
        boolean validado = true;
        validaciones misvalidaciones = new validaciones();

        if (txt_cedula_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione un paciente");
        }

        if (txt_nombre_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese los nombres del paciente");
        }

        if (txt_apellido_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese los apellidos del paciente");
        }

        if (text_budcar_doctor.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione un paciente");
        }
        if (text_diagnositico.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese un diagnostico");
        }
        if (nomb_doctor.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese los nombres del doctor");
        }
        if (apellido_doct.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese los apellidos del doctor");
        }
        if (especialidad_doctor.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la especialidad del doctor");
        }
        if (text_dosis.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese las instrucciones del medicamento");
        }
        if (fecha_inicio_medicamento.getDate() == null) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la fecha de inicio del tratamiento");
        }
        if (fecha_final_medicamento.getDate() == null) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la fecha del fin del tratamiento");
        }

        return validado;
    }
    private void BtBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarPacienteActionPerformed

        if (!text_buscarPacienteDialog.getText().isEmpty()) {
            buscar_paciente(); 
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese la cedula del paciente");
        }
    }//GEN-LAST:event_BtBuscarPacienteActionPerformed
    public void cargarTablaP() {
        DefaultTableModel tb = (DefaultTableModel) TablaPaciente.getModel();
        tb.setNumRows(0);
        List<paciente> com = inser.ListaPaciente();
        com.stream().forEach(p -> {
            String[] cami = {String.valueOf(p.getCodigo()), p.getCedula(), p.getPri_nomb() + "  " + p.getSeg_nombre(), p.getPrim_apell() + "  " + p.getSeg_apelli()};
            tb.addRow(cami);
        });
    }
    private void text_buscarPacienteDialogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_buscarPacienteDialogMousePressed

        text_buscarPacienteDialog.setText("");
        text_buscarPacienteDialog.setForeground(Color.BLACK);

    }//GEN-LAST:event_text_buscarPacienteDialogMousePressed

    private void text_buscarPacienteDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_buscarPacienteDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_buscarPacienteDialogActionPerformed

    private void cargarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarPActionPerformed
        cargar_codigo_paci();
    }//GEN-LAST:event_cargarPActionPerformed

    private void TablaDoctorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDoctorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaDoctorMousePressed

    private void BtBuscarDialogDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarDialogDoctorActionPerformed
        if (!text_buscarDialogDoctor.getText().isEmpty()) {
            buscardoctor(); 
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese la cedula del doctor");
        }
    }//GEN-LAST:event_BtBuscarDialogDoctorActionPerformed

    private void text_buscarDialogDoctorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_buscarDialogDoctorMousePressed
        text_buscarDialogDoctor.setText("");
        text_buscarPacienteDialog.setForeground(Color.BLACK);

    }//GEN-LAST:event_text_buscarDialogDoctorMousePressed

    private void text_buscarDialogDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_buscarDialogDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_buscarDialogDoctorActionPerformed

    private void cargarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarP1ActionPerformed
        cargar_codigo_doctor();
    }//GEN-LAST:event_cargarP1ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (JListMedicamentos.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una enfermedad");
        } else {
            ElimarmedicamentosJlist();
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void buscar_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_doctorActionPerformed

        cargarDoctor.setSize(494, 258);
        cargarTablaE();
        cargarDoctor.setVisible(true);
        cargarDoctor.setLocationRelativeTo(buscar_doctor);

    }//GEN-LAST:event_buscar_doctorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CargarMedicamentosJlist();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void boton_regresar_acceso_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_regresar_acceso_doctorActionPerformed
        // TODO add your handling code here:
        acceso_doctor acdoctor = new acceso_doctor();
        acdoctor.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_regresar_acceso_doctorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (validaciones()) {
            guardar_tratamiento();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        cargarPaciente.setSize(494, 258);
        cargarTablaP();
        cargarPaciente.setVisible(true);
        cargarPaciente.setLocationRelativeTo(buscar);
    }//GEN-LAST:event_buscarActionPerformed
    public void ElimarmedicamentosJlist() {
        if (Listamedicamentos.size() != 0) {
            int indice = JListMedicamentos.getSelectedIndex();
//            System.out.println(indice);
            modeloListMedicamento.remove(indice);
            Listamedicamentos.remove(indice);
        }
    }

    public void cargar_codigo_doctor() {
        int seleccion = TablaDoctor.getSelectedRow();

        if (seleccion == -1) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una fila");
        } else {
            int codigo = Integer.parseInt(TablaDoctor.getValueAt(seleccion, 0).toString());
            inser_doctor.ListaDoctor().forEach((e) -> {
                if (e.getCodigo() == codigo) {
//                    new Agregar_paciente(codigo).setVisible(true);

                    text_budcar_doctor.setText(e.getCedula().toString());
                    nomb_doctor.setText(e.getPri_nomb() + " " + e.getSeg_nombre().toString());
                    apellido_doct.setText(e.getPrim_apell() + " " + e.getSeg_apelli().toString());
                    especialidad_doctor.setText(e.getEspecialidad().toString());

                    cargarDoctor.dispose();
                }
            });

            String cod;
            cod = TablaDoctor.getValueAt(seleccion, 0).toString();
//            System.out.println(cod);
            cargarDoctor.dispose();
        }
    }

    public void cargar_codigo_paci() {
        int seleccion = TablaPaciente.getSelectedRow();

        if (seleccion == -1) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una fila");
        } else {
            int codigo = Integer.parseInt(TablaPaciente.getValueAt(seleccion, 0).toString());
            inser.ListaPaciente().forEach((p) -> {
                if (p.getCodigo() == codigo) {
                    text_codigo_paciente.setText(Integer.toString(p.getCodigo()));
                    txt_cedula_paciente.setText(p.getCedula().toString());
                    txt_nombre_paciente.setText(p.getPri_nomb().toString() + " " + p.getSeg_nombre().toString());
                    txt_apellido_paciente.setText(p.getPrim_apell() + " " + p.getSeg_apelli().toString());

                    cargarPaciente.dispose();
                }
            });

            String cod;
            cod = TablaPaciente.getValueAt(seleccion, 0).toString();
            text_codigo_paciente.setText(cod);
//            System.out.println(cod);
            cargarPaciente.dispose();
        }
    }

    public void guardar_tratamiento() {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        ArrayList array_jlist = new ArrayList();
        String dia = Integer.toString(fecha_inicio_medicamento.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(fecha_inicio_medicamento.getCalendar().get(Calendar.MONTH) + 1);
        String año = Integer.toString(fecha_inicio_medicamento.getCalendar().get(Calendar.YEAR));
        String fecha_inicio_trata = (dia + "-" + mes + "-" + año);

        String dia1 = Integer.toString(fecha_final_medicamento.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes2 = Integer.toString(fecha_final_medicamento.getCalendar().get(Calendar.MONTH) + 1);
        String año3 = Integer.toString(fecha_final_medicamento.getCalendar().get(Calendar.YEAR));
        String fecha_fin_trata = (dia + "-" + mes + "-" + año);
//        mi_trata.setCodigo_medicamento(mi_trata.cargarcodigoMedicina());
        mi_trata.setCodigo_tratamiento(Integer.parseInt(text_codigo_tratamiento.getText()));
        mi_trata.setDiagnostico(text_diagnositico.getText());
        mi_trata.setDosis(text_dosis.getText());
        mi_trata.setFecha_inicio_trata(fecha_inicio_trata);
        mi_trata.setFecha_fin_trata(fecha_fin_trata);

        mi_trata.setCodigo_paciente(Integer.parseInt(text_codigo_paciente.getText()));

        Limpiar();

        if (mi_trata.Insertar_tratamiento()) {
            System.out.println("Conexion Exitosa");
            GuardarTrataMedicamento();
        } else {
            System.out.println("Conexion Erronea");
        }

    }

    public void GuardarTrataMedicamento() {
        for (int i = 0; i < Listamedicamentos.size(); i++) {
            inserTrataMedi.setCodigo_tratamiento(mi_trata.obtenerTratamiento());
            inserTrataMedi.setCodigo_medicamento(Listamedicamentos.get(i).getCodigo_medicamento());
            inserTrataMedi.InsertarTratamientoMedicamento();
        }

    }

    public void LLenarComboBoxMedicamentos() {
        Insert_medicamento inserMedicament = new Insert_medicamento();
        List<medicamentos> com = inserMedicament.ListaMedicamentos();

        for (int i = 0; i < com.size(); i++) {
            ComboMedicamentos.addItem(com.get(i).getNombre_medicamento());
        }
    }

    public void Limpiar() {
        text_budcar_doctor.setText("");
        text_codigo_paciente.setText("");
        text_diagnositico.setText("");
        text_dosis.setText("");
        txt_apellido_paciente.setText("");
        txt_cedula_paciente.setText("");
        txt_nombre_paciente.setText("");
        nomb_doctor.setText("");
        apellido_doct.setText("");
        especialidad_doctor.setText("");

        fecha_inicio_medicamento.setCalendar(null);
        fecha_final_medicamento.setCalendar(null);

        text_dosis.setText("");
    }
    //Cargar medicamentos en JLIST

    public void CargarMedicamentosJlist() {
//       
//
//        if (ComboMedicamentos.getSelectedIndex() == 0) {
//            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado un medicamento");
//        } else {
//
//            DefaultListModel modeloListMedicamento;
//            modeloListMedicamento = new DefaultListModel();
//            JListMedicamentos.setModel(modeloListMedicamento);
//
//            String medicaAux;
//            medicaAux = ComboMedicamentos.getSelectedItem().toString();
//            mi_medicamento.setNombre_medicamento(medicaAux);
//
//            Listamedicamentos.add(mi_medicamento);
//
//            for (int i = 0; i < Listamedicamentos.size(); i++) {
//
//                modeloListMedicamento.addElement(Listamedicamentos.get(i).getNombre_medicamento());
//                ComboMedicamentos.setSelectedIndex(0);
//            }
//
//        }

        medicamentos mi_medicamento = new medicamentos();
        boolean rep = false;
        if (ComboMedicamentos.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una enfermedad");
        } else {

//            DefaultListModel modeloListEnfermedad;
            modeloListMedicamento = new DefaultListModel();
            JListMedicamentos.setModel(modeloListMedicamento);

            String nomb_medi = ComboMedicamentos.getSelectedItem().toString();

            mi_medicamento.setNombre_medicamento(nomb_medi);
            mi_medicamento.setCodigo_medicamento(mi_trata.cargarcodigoMedicina(nomb_medi));
            if (Listamedicamentos.size() != 0) {
                for (int i = 0; i < Listamedicamentos.size(); i++) {
                    rep = false;
                    if (nomb_medi.equalsIgnoreCase(Listamedicamentos.get(i).getNombre_medicamento())) {

                        rep = true;
                        i = Listamedicamentos.size();
                    }
                }
            } else {
                rep = true;
                Listamedicamentos.add(mi_medicamento);
            }
            if (rep == false) {
                Listamedicamentos.add(mi_medicamento);
            }

            for (int i = 0; i < Listamedicamentos.size(); i++) {

                modeloListMedicamento.addElement(Listamedicamentos.get(i).getNombre_medicamento());
                ComboMedicamentos.setSelectedIndex(0);
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregar_tratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregar_tratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregar_tratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregar_tratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregar_tratamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscarDialogDoctor;
    private javax.swing.JButton BtBuscarPaciente;
    private javax.swing.JComboBox<String> ComboMedicamentos;
    private javax.swing.JButton Eliminar;
    private javax.swing.JList<String> JListMedicamentos;
    private javax.swing.JTable TablaDoctor;
    private javax.swing.JTable TablaPaciente;
    private javax.swing.JTextField apellido_doct;
    private javax.swing.JButton boton_regresar_acceso_doctor;
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscar_doctor;
    private javax.swing.JDialog cargarDoctor;
    private javax.swing.JButton cargarP;
    private javax.swing.JButton cargarP1;
    private javax.swing.JDialog cargarPaciente;
    private javax.swing.JTextField especialidad_doctor;
    private com.toedter.calendar.JDateChooser fecha_final_medicamento;
    private com.toedter.calendar.JDateChooser fecha_inicio_medicamento;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nomb_doctor;
    private javax.swing.JTextField text_budcar_doctor;
    private javax.swing.JTextField text_buscarDialogDoctor;
    private javax.swing.JTextField text_buscarPacienteDialog;
    private javax.swing.JTextField text_codigo_paciente;
    private javax.swing.JTextField text_codigo_tratamiento;
    private javax.swing.JTextArea text_diagnositico;
    private javax.swing.JTextArea text_dosis;
    private javax.swing.JTextField txt_apellido_paciente;
    private javax.swing.JTextField txt_cedula_paciente;
    private javax.swing.JTextField txt_nombre_paciente;
    // End of variables declaration//GEN-END:variables
}
