package ventanas;

import java.awt.Color;
import clases.recepcionista;
import clases.usuario;
//import conexion_bada.Insert_doctor;
//import conexion_bada.Insert;
import conexion_bada.Insert_recepcionista;
import conexion_bada.Insert_usuario;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import clases.validaciones;
import conexion_bada.Conexion;
import conexion_bada.Insert_Persona;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Agregar_recepcionista extends javax.swing.JFrame {

    Conexion mi_cone = new Conexion();
    Insert_usuario usu = new Insert_usuario();
    Insert_recepcionista recep = new Insert_recepcionista();
    validaciones misvalidaciones = new validaciones();
    String hora_ingresoAux;
    String hora_salidaAux;

    DateFormat df = DateFormat.getDateInstance();
    ArrayList<recepcionista> lista_recepcionista = new ArrayList();

    public Agregar_recepcionista() {
        initComponents();
        this.setLocationRelativeTo(null);
        modificar.setVisible(false);
        cargarcod();
    }

    public Agregar_recepcionista(String cedula) {
        initComponents();
        this.setLocationRelativeTo(null);
        Guardar_recepcionista.setVisible(false);
        String SQL_SELECT = "SELECT * FROM recepcionista WHERE cedula = " + cedula + ";";
        llenar_recepcionista(cedula);
        
    }

    public void llenar_recepcionista(String cedula) {
        text_cedula_recepcionista.setEnabled(false);
        text_codigo_recepcionista.setEnabled(false);
        List<recepcionista> com = recep.ListaRecepcionista();
        com.stream().forEach(p -> {
            if (cedula.equalsIgnoreCase(p.getCedula())) {
                text_codigo_recepcionista.setText(String.valueOf(p.getCodigo()));
                text_cedula_recepcionista.setText(p.getCedula().toString());
                text_PrimerNombre_recepcionista.setText(p.getPri_nomb().toString());
                text_SegundoNombre_recepcionista.setText(p.getSeg_nombre().toString());
                text_PrimerApellido_recepcionista.setText(p.getPrim_apell().toString());
                text_segundoApellido_recepcionista.setText(p.getSeg_apelli().toString());
                text_email_recepcionista.setText(p.getCorreo().toString());
                text_direccion_recepcionista.setText(p.getDireccion());
                text_celular_recepcionista.setText(p.getTelefono());
                if (p.getGenero().equalsIgnoreCase("hombre")) {
                    Masculino_recepcionista.setSelected(true);
                }
                if (p.getGenero().equalsIgnoreCase("mujer")) {
                    Femenino_recepcionista.setSelected(true);
                }

                Spinner_HoraEntrada_recepcionista.setValue(Integer.parseInt(p.getHora_ingreso().substring(0, 2)));
                Spinner_MinutosEntrada_recepcionista.setValue(Integer.parseInt(p.getHora_ingreso().substring(3, 5)));

                Spinner_HoraSalida_recepcionista.setValue(Integer.parseInt(p.getHora_salida().substring(0, 2)));
                Spinner_MinutosSalida_recepcionista.setValue(Integer.parseInt(p.getHora_salida().substring(3, 5)));

                SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
                Date fecha = null;
                try {
                    fecha = formatofecha.parse(p.getFecha_Nacimiento());
                } catch (ParseException ex) {
                    Logger.getLogger(Agregar_administrador.class.getName()).log(Level.SEVERE, null, ex);
                }
                Fecha_Nacimiento_recepcionista.setDate(fecha);

                for (int j = 0; j < combo_sangre_recepcionista.getItemCount(); j++) {
                    if (combo_sangre_recepcionista.getItemAt(j).equalsIgnoreCase(p.getTipo_sangre())) {
                        combo_sangre_recepcionista.setSelectedIndex(j);
                        j = combo_sangre_recepcionista.getItemCount();
                    }
                }
                List<usuario> usua = usu.ListaUsuariosModi(String.valueOf(p.getCod_usuario()), "recepcionista", "recep");
                usua.stream().forEach(u -> {
                    txt_usuario.setText(u.getUsuario());
                    txt_contrasena.setText(u.getContraseña());
                });
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        Genero_recepcionista = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        text_cedula_recepcionista = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        text_SegundoNombre_recepcionista = new javax.swing.JTextField();
        text_PrimerNombre_recepcionista = new javax.swing.JTextField();
        text_codigo_recepcionista = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        text_PrimerApellido_recepcionista = new javax.swing.JTextField();
        text_segundoApellido_recepcionista = new javax.swing.JTextField();
        Femenino_recepcionista = new javax.swing.JRadioButton();
        Masculino_recepcionista = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Spinner_HoraSalida_recepcionista = new javax.swing.JSpinner();
        Spinner_MinutosEntrada_recepcionista = new javax.swing.JSpinner();
        Spinner_HoraEntrada_recepcionista = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        Fecha_Nacimiento_recepcionista = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        text_email_recepcionista = new javax.swing.JTextField();
        text_celular_recepcionista = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        combo_sangre_recepcionista = new javax.swing.JComboBox<>();
        Regresar_recepcionista = new javax.swing.JButton();
        Guardar_recepcionista = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Spinner_MinutosSalida_recepcionista = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        modificar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_contrasena = new javax.swing.JTextField();
        text_direccion_recepcionista = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 239, 180));

        text_cedula_recepcionista.setForeground(new java.awt.Color(102, 102, 102));
        text_cedula_recepcionista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_cedula_recepcionista.setText("Ingrese la Cedula");
        text_cedula_recepcionista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_cedula_recepcionistaFocusLost(evt);
            }
        });
        text_cedula_recepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_cedula_recepcionistaMousePressed(evt);
            }
        });
        text_cedula_recepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cedula_recepcionistaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Cédula:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Código:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Datos Personales");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text_SegundoNombre_recepcionista.setForeground(new java.awt.Color(102, 102, 102));
        text_SegundoNombre_recepcionista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_SegundoNombre_recepcionista.setText("Ingrese el Segundo Nombre");
        text_SegundoNombre_recepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_SegundoNombre_recepcionistaMousePressed(evt);
            }
        });

        text_PrimerNombre_recepcionista.setForeground(new java.awt.Color(102, 102, 102));
        text_PrimerNombre_recepcionista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_PrimerNombre_recepcionista.setText("Ingrese el Primer Nombre");
        text_PrimerNombre_recepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_PrimerNombre_recepcionistaMousePressed(evt);
            }
        });
        text_PrimerNombre_recepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_PrimerNombre_recepcionistaActionPerformed(evt);
            }
        });

        text_codigo_recepcionista.setForeground(new java.awt.Color(102, 102, 102));
        text_codigo_recepcionista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_codigo_recepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_codigo_recepcionistaMousePressed(evt);
            }
        });
        text_codigo_recepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_codigo_recepcionistaActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        text_PrimerApellido_recepcionista.setForeground(new java.awt.Color(102, 102, 102));
        text_PrimerApellido_recepcionista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_PrimerApellido_recepcionista.setText("Ingrese el Primer Apellido");
        text_PrimerApellido_recepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_PrimerApellido_recepcionistaMousePressed(evt);
            }
        });
        text_PrimerApellido_recepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_PrimerApellido_recepcionistaActionPerformed(evt);
            }
        });

        text_segundoApellido_recepcionista.setForeground(new java.awt.Color(102, 102, 102));
        text_segundoApellido_recepcionista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_segundoApellido_recepcionista.setText("Ingrese el Segundo Apellido");
        text_segundoApellido_recepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_segundoApellido_recepcionistaMousePressed(evt);
            }
        });

        Genero_recepcionista.add(Femenino_recepcionista);
        Femenino_recepcionista.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Femenino_recepcionista.setText("F");
        Femenino_recepcionista.setOpaque(false);

        Genero_recepcionista.add(Masculino_recepcionista);
        Masculino_recepcionista.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Masculino_recepcionista.setText("M");
        Masculino_recepcionista.setOpaque(false);
        Masculino_recepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masculino_recepcionistaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Sexo:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Hora de Ingreso");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Hora de Salida");

        Spinner_HoraSalida_recepcionista.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        Spinner_MinutosEntrada_recepcionista.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        Spinner_HoraEntrada_recepcionista.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Fecha de nacimiento:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Primer Apellido:");

        text_email_recepcionista.setForeground(new java.awt.Color(102, 102, 102));
        text_email_recepcionista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_email_recepcionista.setText("Ingrese el E-mail");
        text_email_recepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_email_recepcionistaMousePressed(evt);
            }
        });

        text_celular_recepcionista.setForeground(new java.awt.Color(102, 102, 102));
        text_celular_recepcionista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_celular_recepcionista.setText("Ingrese el celular");
        text_celular_recepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_celular_recepcionistaMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Email:");

        combo_sangre_recepcionista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        Regresar_recepcionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        Regresar_recepcionista.setToolTipText("REGRESAR");
        Regresar_recepcionista.setBorder(null);
        Regresar_recepcionista.setOpaque(false);
        Regresar_recepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar_recepcionistaActionPerformed(evt);
            }
        });

        Guardar_recepcionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salvar (1).png"))); // NOI18N
        Guardar_recepcionista.setToolTipText("GUARDAR");
        Guardar_recepcionista.setBorder(null);
        Guardar_recepcionista.setOpaque(false);
        Guardar_recepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_recepcionistaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Segundo Apellido:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Tipo de Sangre:");

        Spinner_MinutosSalida_recepcionista.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR RECEPCIONISTA");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("NUEVO USUARIO:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("NUEVA CONTRASEÑA:");

        txt_usuario.setForeground(new java.awt.Color(102, 102, 102));
        txt_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_usuario.setText("Ej: Usuario1");
        txt_usuario.setToolTipText("El usuario debe contener minimo 3 letras y 1 numero");
        txt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_usuarioMousePressed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar (1).png"))); // NOI18N
        modificar.setToolTipText("MODIFICAR");
        modificar.setBorder(null);
        modificar.setOpaque(false);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Hora");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Minutos");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Hora");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Minutos");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Primer Nombre:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Segundo Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("CREAR USUARIO");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_contrasena.setForeground(new java.awt.Color(102, 102, 102));
        txt_contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_contrasena.setText("Ej: Pass1@");
        txt_contrasena.setToolTipText("Debe contener minimo 1 letra minus, 1 mayus, 1 numero y un caracter especial, minimo 5caract. y max 20");
        txt_contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_contrasenaMousePressed(evt);
            }
        });

        text_direccion_recepcionista.setForeground(new java.awt.Color(102, 102, 102));
        text_direccion_recepcionista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_direccion_recepcionista.setText("Ingrese la Direccion");
        text_direccion_recepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_direccion_recepcionistaMousePressed(evt);
            }
        });
        text_direccion_recepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_direccion_recepcionistaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Dirección:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Celular:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(314, 314, 314)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel11)
                        .addComponent(jLabel2)
                        .addComponent(jLabel24)
                        .addComponent(jLabel17))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(text_celular_recepcionista)
                        .addComponent(text_SegundoNombre_recepcionista, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(text_PrimerNombre_recepcionista, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(text_PrimerApellido_recepcionista, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(text_email_recepcionista, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(text_cedula_recepcionista, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(text_segundoApellido_recepcionista, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(text_direccion_recepcionista))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(32, 32, 32)
                                    .addComponent(Fecha_Nacimiento_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(Masculino_recepcionista)
                                    .addGap(18, 18, 18)
                                    .addComponent(Femenino_recepcionista))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(26, 26, 26)
                                    .addComponent(text_codigo_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(35, 35, 35)
                                    .addComponent(combo_sangre_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(jLabel20)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel21))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(Spinner_HoraEntrada_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Spinner_MinutosEntrada_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(41, 41, 41)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Spinner_HoraSalida_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(jLabel22)))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Spinner_MinutosSalida_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel23)))))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel18))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_contrasena)
                                        .addComponent(txt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(Guardar_recepcionista)
                .addGap(94, 94, 94)
                .addComponent(modificar)
                .addGap(94, 94, 94)
                .addComponent(Regresar_recepcionista))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_codigo_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17)
                                        .addComponent(text_cedula_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(text_PrimerNombre_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Fecha_Nacimiento_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))))
                    .addComponent(jLabel24))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_SegundoNombre_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Masculino_recepcionista)
                            .addComponent(Femenino_recepcionista))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(combo_sangre_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_PrimerApellido_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(text_segundoApellido_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(31, 31, 31)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(text_email_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5))
                                                .addGap(38, 38, 38)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(text_direccion_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(Spinner_HoraSalida_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(Spinner_MinutosSalida_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(Spinner_HoraEntrada_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(Spinner_MinutosEntrada_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel20)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel22)
                                                        .addComponent(jLabel23)))
                                                .addGap(49, 49, 49)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel18))))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(text_celular_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19)
                                            .addComponent(txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(251, 251, 251)
                                        .addComponent(jLabel12)))
                                .addGap(49, 49, 49)
                                .addComponent(modificar))
                            .addComponent(Regresar_recepcionista, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Guardar_recepcionista)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "¿Seguro que desea modificarlo?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            modificar_recepcionista();
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void Guardar_recepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_recepcionistaActionPerformed
        try {
            RegistrarRecepcionista();
        } catch (SQLException ex) {
            Logger.getLogger(Agregar_administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Guardar_recepcionistaActionPerformed

    private void Regresar_recepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar_recepcionistaActionPerformed
        this.dispose();
        new crud_recepcionista().setVisible(true);
    }//GEN-LAST:event_Regresar_recepcionistaActionPerformed

    private void text_celular_recepcionistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_celular_recepcionistaMousePressed
        text_celular_recepcionista.setText("");
        text_celular_recepcionista.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_celular_recepcionistaMousePressed

    private void text_email_recepcionistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_email_recepcionistaMousePressed
        text_email_recepcionista.setText("");
        text_email_recepcionista.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_email_recepcionistaMousePressed

    private void Masculino_recepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masculino_recepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Masculino_recepcionistaActionPerformed

    private void text_segundoApellido_recepcionistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_segundoApellido_recepcionistaMousePressed
        text_segundoApellido_recepcionista.setText("");
        text_segundoApellido_recepcionista.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_segundoApellido_recepcionistaMousePressed

    private void text_PrimerApellido_recepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_PrimerApellido_recepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerApellido_recepcionistaActionPerformed

    private void text_PrimerApellido_recepcionistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_PrimerApellido_recepcionistaMousePressed
        text_PrimerApellido_recepcionista.setText("");
        text_PrimerApellido_recepcionista.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerApellido_recepcionistaMousePressed

    private void text_codigo_recepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_codigo_recepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_codigo_recepcionistaActionPerformed

    private void text_codigo_recepcionistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_codigo_recepcionistaMousePressed
        //        text_codigo_recepcionista.setText("");
        //        text_codigo_recepcionista.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_codigo_recepcionistaMousePressed

    private void text_PrimerNombre_recepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_PrimerNombre_recepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerNombre_recepcionistaActionPerformed

    private void text_PrimerNombre_recepcionistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_PrimerNombre_recepcionistaMousePressed
        text_PrimerNombre_recepcionista.setText("");
        text_PrimerNombre_recepcionista.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerNombre_recepcionistaMousePressed

    private void text_SegundoNombre_recepcionistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_SegundoNombre_recepcionistaMousePressed
        text_SegundoNombre_recepcionista.setText("");
        text_SegundoNombre_recepcionista.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoNombre_recepcionistaMousePressed

    private void text_cedula_recepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cedula_recepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cedula_recepcionistaActionPerformed

    private void text_cedula_recepcionistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_cedula_recepcionistaMousePressed
        if (text_cedula_recepcionista.getText().equalsIgnoreCase("Ingrese la cedula")) {
            text_cedula_recepcionista.setText("");
        }
        text_cedula_recepcionista.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_cedula_recepcionistaMousePressed

    private void text_cedula_recepcionistaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_cedula_recepcionistaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cedula_recepcionistaFocusLost

    private void text_direccion_recepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_direccion_recepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccion_recepcionistaActionPerformed

    private void text_direccion_recepcionistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_direccion_recepcionistaMousePressed
        // TODO add your handling code here:
        text_direccion_recepcionista.setText("");
        text_direccion_recepcionista.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_direccion_recepcionistaMousePressed

    private void txt_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMousePressed
        // TODO add your handling code here:
        txt_usuario.setText("");
        txt_usuario.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_usuarioMousePressed

    private void txt_contrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contrasenaMousePressed
        // TODO add your handling code here:
        txt_contrasena.setText("");
        txt_contrasena.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_contrasenaMousePressed
    public void modificar_recepcionista() {
        String genero = "";
        if (Masculino_recepcionista.isSelected()) {
            genero = "hombre";
        }
        if (Femenino_recepcionista.isSelected()) {
            genero = "mujer";
        }
        String tipoo_sangre = combo_sangre_recepcionista.getSelectedItem().toString();

        String dia = Integer.toString(Fecha_Nacimiento_recepcionista.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(Fecha_Nacimiento_recepcionista.getCalendar().get(Calendar.MONTH) + 1);
        String año = Integer.toString(Fecha_Nacimiento_recepcionista.getCalendar().get(Calendar.YEAR));
        String FechaNacimiento = (dia + "-" + mes + "-" + año);
        String Hingreso, Mingreso, Hsalida, Msalida;
        Hingreso = Spinner_HoraEntrada_recepcionista.getValue().toString();
        Mingreso = Spinner_MinutosEntrada_recepcionista.getValue().toString();
        Hsalida = Spinner_HoraSalida_recepcionista.getValue().toString();
        Msalida = Spinner_MinutosSalida_recepcionista.getValue().toString();

        if (String.valueOf(Hingreso).length() == 1) {
            Hingreso = "0" + Hingreso;
        }
        if (String.valueOf(Mingreso).length() == 1) {
            Mingreso = "0" + Mingreso;
        }

        if (String.valueOf(Hsalida).length() == 1) {
            Hsalida = "0" + Hsalida;
        }
        if (String.valueOf(Msalida).length() == 1) {
            Msalida = "0" + Msalida;
        }

        hora_ingresoAux = Hingreso + ":" + Mingreso;
        hora_salidaAux = Hsalida + ":" + Msalida;

        mi_cone.InsertUpdateDeleteAcciones("UPDATE persona per SET  per_primer_nombre='" + text_PrimerNombre_recepcionista.getText() + "', per_segundo_nombre='" + text_SegundoNombre_recepcionista.getText() + "'"
                + ", per_primer_apellido='" + text_PrimerApellido_recepcionista.getText() + "', per_segundo_apellido='" + text_segundoApellido_recepcionista.getText() + "'"
                + ", per_correo='" + text_email_recepcionista.getText() + "', per_genero='" + genero + "', per_direccion='" + text_direccion_recepcionista.getText() + "', per_telefono='" + text_celular_recepcionista.getText() + "', per_tipo_sangre='" + tipoo_sangre + "',per_fecha_nacimiento='" + FechaNacimiento + "' WHERE per_cedula='" + text_cedula_recepcionista.getText() + "'");

        mi_cone.InsertUpdateDeleteAcciones("UPDATE recepcionista SET recep_hora_ingreso='" + hora_ingresoAux + "',recep_hora_salida='" + hora_salidaAux + "' WHERE recep_cedula='" + text_cedula_recepcionista.getText() + "'");
        
        mi_cone.InsertUpdateDeleteAcciones("UPDATE usuario SET us_usuario='" + txt_usuario.getText() + "', us_contrasena='" + txt_contrasena.getText() + "' WHERE us_codigo='" + recep.cargarcodigoUSER(text_cedula_recepcionista.getText()) + "'");
    
        limpiar();
        JOptionPane.showMessageDialog(null,"El registro se modifico correctamente");
    }

    public void cargarcod() {
        text_codigo_recepcionista.setEnabled(false);
        text_codigo_recepcionista.setText(String.valueOf(recep.cargarcodigo()));
    }

    public void RegistrarRecepcionista() throws SQLException {

        Insert_Persona per = new Insert_Persona();
        try {
            if (validaciones()) {
                if (per.validarduplicado(text_cedula_recepcionista.getText())) {
                    if (usu.validarNomduplicado(txt_usuario.getText())) {
                        String genero = "";

                        recep.setCodigo(Integer.parseInt(text_codigo_recepcionista.getText()));
                        recep.setCedula(text_cedula_recepcionista.getText());
                        recep.setPri_nomb(text_PrimerNombre_recepcionista.getText());
                        recep.setSeg_nombre(text_SegundoNombre_recepcionista.getText());
                        recep.setPrim_apell(text_PrimerApellido_recepcionista.getText());
                        recep.setSeg_apelli(text_segundoApellido_recepcionista.getText());
                        recep.setDireccion(text_direccion_recepcionista.getText());
                        if (Masculino_recepcionista.isSelected()) {
                            genero = "hombre";
                        }
                        if (Femenino_recepcionista.isSelected()) {
                            genero = "mujer";
                        }
                        recep.setGenero(genero);

                        String dia = Integer.toString(Fecha_Nacimiento_recepcionista.getCalendar().get(Calendar.DAY_OF_MONTH));
                        String mes = Integer.toString(Fecha_Nacimiento_recepcionista.getCalendar().get(Calendar.MONTH) + 1);
                        String año = Integer.toString(Fecha_Nacimiento_recepcionista.getCalendar().get(Calendar.YEAR));
                        String FechaNacimiento = (dia + "-" + mes + "-" + año);
                        recep.setFecha_Nacimiento(FechaNacimiento);

                        recep.setCorreo(text_email_recepcionista.getText());
                        recep.setTelefono(text_celular_recepcionista.getText());
                        recep.setTipo_sangre(combo_sangre_recepcionista.getSelectedItem().toString());

                        String Hingreso, Mingreso, Hsalida, Msalida;
                        Hingreso = Spinner_HoraEntrada_recepcionista.getValue().toString();
                        Mingreso = Spinner_MinutosEntrada_recepcionista.getValue().toString();
                        Hsalida = Spinner_HoraSalida_recepcionista.getValue().toString();
                        Msalida = Spinner_MinutosSalida_recepcionista.getValue().toString();

                        if (String.valueOf(Hingreso).length() == 1) {
                            Hingreso = "0" + Hingreso;
                        }
                        if (String.valueOf(Mingreso).length() == 1) {
                            Mingreso = "0" + Mingreso;
                        }

                        if (String.valueOf(Hsalida).length() == 1) {
                            Hsalida = "0" + Hsalida;
                        }
                        if (String.valueOf(Msalida).length() == 1) {
                            Msalida = "0" + Msalida;
                        }

                        hora_ingresoAux = Hingreso + ":" + Mingreso;
                        hora_salidaAux = Hsalida + ":" + Msalida;
                        recep.setHora_ingreso(hora_ingresoAux);
                        recep.setHora_salida(hora_salidaAux);
                        recep.setCod_usuario(usu.obtenerUsuario());
                        recep.InsertarPersona();

                        usu.setUsuario(txt_usuario.getText());
                        usu.setContraseña(txt_contrasena.getText());
                        usu.InsertarUsuario();
                        recep.setCod_usuario(usu.obtenerUsuario());

                        if (recep.InsertarRecepcionista()) {
                            JOptionPane.showMessageDialog(null, "La recepcionista se guardo exitosamente");
                            limpiar();
                            cargarcod();
                        } else {
                            JOptionPane.showMessageDialog(null,"Larecepcionista no se guardo correctamente");
                            //System.out.println("Conexion Erronea");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "El nombre de usuario ya existe");
                        txt_usuario.setText("");

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "La recepcionista ya existe en el sistema");
                    text_cedula_recepcionista.setText("");

                }
            }
        } catch (NullPointerException n) {

        }
    }

    public boolean validaciones() {
        boolean validado = true;

        if (text_cedula_recepcionista.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la cedula");
        } else {
            if (!misvalidaciones.validar_cedula(text_cedula_recepcionista.getText())) {
                JOptionPane.showMessageDialog(this, "Cedula incorrecta");
                validado = false;
            }
        }

        if (text_PrimerNombre_recepcionista.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el primer nombre");
        } else {
            if (!misvalidaciones.validar_nombre_apellido(text_PrimerNombre_recepcionista.getText())) {
                JOptionPane.showMessageDialog(this, "Primer nombre incorrecto");
                validado = false;
            }
        }
        if (text_SegundoNombre_recepcionista.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el segundo nombre");
        } else {
            if (!misvalidaciones.validar_nombre_apellido(text_SegundoNombre_recepcionista.getText())) {
                JOptionPane.showMessageDialog(this, "Segundo nombre incorrecto");
                validado = false;
            }
        }
        if (text_PrimerApellido_recepcionista.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el primer apellido");
        } else {
            if (!misvalidaciones.validar_nombre_apellido(text_PrimerApellido_recepcionista.getText())) {
                JOptionPane.showMessageDialog(this, "Primer apellido incorrecto");
                validado = false;
            }
        }
        if (text_segundoApellido_recepcionista.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el segundo apellido");
        } else {
            if (!misvalidaciones.validar_nombre_apellido(text_segundoApellido_recepcionista.getText())) {
                JOptionPane.showMessageDialog(this, "Segundo apellido incorrecto");
                validado = false;
            }
        }
        if (text_direccion_recepcionista.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la direccion");
        } else {
            if (!misvalidaciones.validarDireccion(text_direccion_recepcionista.getText())) {
                JOptionPane.showMessageDialog(this, "Direccion invalida");
                validado = false;
            }
        }
        if (text_cedula_recepcionista.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el celular");
        } else {
            if (!misvalidaciones.validarTelefono(text_cedula_recepcionista.getText())) {
                JOptionPane.showMessageDialog(this, "Celular invalido");
                validado = false;
            }
        }
        if (text_email_recepcionista.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el correo");
        } else {
            if (!misvalidaciones.validarCorreo(text_email_recepcionista.getText())) {
                JOptionPane.showMessageDialog(this, "Correo invalido");
                validado = false;
            }
        }

        if (txt_usuario.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese un usuario");
        } else {
            if (!misvalidaciones.validarUsuario(txt_usuario.getText())) {
                JOptionPane.showMessageDialog(this, "Usuario invalido");
                validado = false;
            }
        }

        if (txt_contrasena.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese una contraseña");
        } else {
            if (!misvalidaciones.validarContrasena(txt_contrasena.getText())) {
                JOptionPane.showMessageDialog(this, "Contraseña invalida");
                validado = false;
            }
        }

        if ((Integer) Spinner_HoraEntrada_recepcionista.getValue() == 0) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Hora de entrada invalida");
        }
        if ((Integer) Spinner_HoraSalida_recepcionista.getValue() == 0) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Hora de salida invalida");
        }

        if (combo_sangre_recepcionista.getSelectedIndex() == 0) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione el tipo de sangre");
        }
        if (Fecha_Nacimiento_recepcionista.getDate() == null) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la fecha de nacimiento del administrador");
        }

        if (!Masculino_recepcionista.isSelected() && !Femenino_recepcionista.isSelected()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "seleccione un genero");
        }

        return validado;
    }

    public void limpiar() {
        text_codigo_recepcionista.setText("");
        text_cedula_recepcionista.setText("");
        text_PrimerNombre_recepcionista.setText("");
        text_SegundoNombre_recepcionista.setText("");
        text_PrimerApellido_recepcionista.setText("");
        text_segundoApellido_recepcionista.setText("");
        text_direccion_recepcionista.setText("");
        text_email_recepcionista.setText("");
        text_celular_recepcionista.setText("");
        Genero_recepcionista.clearSelection();
        Spinner_HoraEntrada_recepcionista.setValue(0);
        Spinner_HoraSalida_recepcionista.setValue(0);
        combo_sangre_recepcionista.setSelectedIndex(0);
        Fecha_Nacimiento_recepcionista.setCalendar(null);
        txt_usuario.setText("");
        txt_contrasena.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_recepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha_Nacimiento_recepcionista;
    private javax.swing.JRadioButton Femenino_recepcionista;
    private javax.swing.ButtonGroup Genero_recepcionista;
    private javax.swing.JButton Guardar_recepcionista;
    private javax.swing.JRadioButton Masculino_recepcionista;
    private javax.swing.JButton Regresar_recepcionista;
    private javax.swing.JSpinner Spinner_HoraEntrada_recepcionista;
    private javax.swing.JSpinner Spinner_HoraSalida_recepcionista;
    private javax.swing.JSpinner Spinner_MinutosEntrada_recepcionista;
    private javax.swing.JSpinner Spinner_MinutosSalida_recepcionista;
    private javax.swing.JComboBox<String> combo_sangre_recepcionista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField text_PrimerApellido_recepcionista;
    private javax.swing.JTextField text_PrimerNombre_recepcionista;
    private javax.swing.JTextField text_SegundoNombre_recepcionista;
    private javax.swing.JTextField text_cedula_recepcionista;
    private javax.swing.JTextField text_celular_recepcionista;
    private javax.swing.JTextField text_codigo_recepcionista;
    private javax.swing.JTextField text_direccion_recepcionista;
    private javax.swing.JTextField text_email_recepcionista;
    private javax.swing.JTextField text_segundoApellido_recepcionista;
    private javax.swing.JTextField txt_contrasena;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
