package ventanas;

import clases.alergias;
import conexion_bada.Insert_alergias;
import clases.enfermedades;
import conexion_bada.insert_enfermedad;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

import clases.paciente;
import conexion_bada.Insert;
import conexion_bada.insert_ficha_medica;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public class FichaMedica extends javax.swing.JFrame {
    insert_ficha_medica mi_ficha=new insert_ficha_medica();
    Insert inser = new Insert();

    public FichaMedica() {
        initComponents();
        this.setLocationRelativeTo(null);
        LLenarComboBoxAlergias();
        LLenarComboBoxEnfermedades();
        BloquearCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruposexoficha = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcodigoficha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodigopaciente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnombrefm = new javax.swing.JTextField();
        txtsegundonombrefm = new javax.swing.JTextField();
        txtapellidofm = new javax.swing.JTextField();
        txtsegundoapellidofm = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtcedulafm = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtcorreofm = new javax.swing.JTextField();
        txtdireccionfm = new javax.swing.JTextField();
        txttelefonofm = new javax.swing.JTextField();
        masculinoficha = new javax.swing.JRadioButton();
        femeninoficha = new javax.swing.JRadioButton();
        comboenfermedadficha = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        comboalergiaficha = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtobservacionesficha = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        CheckBoxSeguro = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTipoSangre = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JListAlergias = new javax.swing.JList<>();
        CargarAlergias = new javax.swing.JButton();
        CargarEnfermedades = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JListEnfermedades = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel2.setText("Codigo de Ficha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 110, 20));

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel7.setText("Primer Apellido:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DATOS PERSONALES");
        jLabel8.setToolTipText("");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FICHA MEDICA");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 220, 50));

        txtcodigoficha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigofichaActionPerformed(evt);
            }
        });
        jPanel1.add(txtcodigoficha, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 140, 30));

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel5.setText("Segundo Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel3.setText("Codigo de Paciente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel6.setText("Segundo Apellido:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, -1));

        txtcodigopaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigopacienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtcodigopaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 140, 30));

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel4.setText("Primer Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel1.add(txtnombrefm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, 30));

        txtsegundonombrefm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsegundonombrefmActionPerformed(evt);
            }
        });
        jPanel1.add(txtsegundonombrefm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 180, 30));

        txtapellidofm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidofmActionPerformed(evt);
            }
        });
        jPanel1.add(txtapellidofm, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 180, 30));
        jPanel1.add(txtsegundoapellidofm, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 160, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 840, 20));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel9.setText("Cedula:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 102, 890, 10));
        jPanel1.add(txtcedulafm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 180, 30));

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel10.setText("Correo Electronico:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel11.setText("Telefono:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel12.setText("Sexo:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel13.setText("Direccion:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel14.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel14.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel15.setText("Tipo de Sangre:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ANTECEDENTES MEDICOS ");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 220, 30));

        jLabel17.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel17.setText("ENFERMEDADES:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));
        jPanel1.add(txtcorreofm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 210, 30));
        jPanel1.add(txtdireccionfm, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 280, 30));
        jPanel1.add(txttelefonofm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 160, 30));

        masculinoficha.setBackground(new java.awt.Color(204, 204, 204));
        masculinoficha.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        masculinoficha.setText("M");
        jPanel1.add(masculinoficha, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, -1, -1));

        femeninoficha.setBackground(new java.awt.Color(204, 204, 204));
        femeninoficha.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        femeninoficha.setText("F");
        jPanel1.add(femeninoficha, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, -1, -1));

        comboenfermedadficha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));
        jPanel1.add(comboenfermedadficha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 160, 30));

        jLabel19.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel19.setText("ALERGIAS:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 90, -1));

        comboalergiaficha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));
        jPanel1.add(comboalergiaficha, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 160, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 720, 20));

        jLabel20.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("OBSERVACIONES");
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 160, 30));

        txtobservacionesficha.setColumns(20);
        txtobservacionesficha.setRows(5);
        jScrollPane1.setViewportView(txtobservacionesficha);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 840, -1));

        jLabel21.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel21.setText("Fecha de registro:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel22.setText("Tiene Seguro Medico:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 140, 30));

        CheckBoxSeguro.setBackground(new java.awt.Color(204, 204, 204));
        CheckBoxSeguro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBoxSeguro.setText("SI");
        CheckBoxSeguro.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel1.add(CheckBoxSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 40, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/medical-history.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salvar (1).png"))); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, -1, -1));
        jPanel1.add(txtTipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 70, 30));
        jPanel1.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 140, 30));

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        Buscar.setToolTipText("buscar paciente");
        Buscar.setBorder(null);
        Buscar.setOpaque(false);
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jScrollPane2.setViewportView(JListAlergias);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 160, 80));

        CargarAlergias.setText("Cargar");
        CargarAlergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarAlergiasActionPerformed(evt);
            }
        });
        jPanel1.add(CargarAlergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 400, -1, -1));

        CargarEnfermedades.setText("Cargar");
        CargarEnfermedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarEnfermedadesActionPerformed(evt);
            }
        });
        jPanel1.add(CargarEnfermedades, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        jScrollPane3.setViewportView(JListEnfermedades);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 160, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigofichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigofichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigofichaActionPerformed

    private void txtcodigopacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigopacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigopacienteActionPerformed

    private void txtsegundonombrefmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsegundonombrefmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsegundonombrefmActionPerformed

    private void txtapellidofmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidofmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidofmActionPerformed

    private void CargarAlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarAlergiasActionPerformed
        CargarAlergiasJlist();
    }//GEN-LAST:event_CargarAlergiasActionPerformed

    private void CargarEnfermedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarEnfermedadesActionPerformed

        CargarEnfermedadesJlist();
    }//GEN-LAST:event_CargarEnfermedadesActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        buscar_paciente();
    }//GEN-LAST:event_BuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void guardarficha(){
        
        
        
        
        
        
        
    }
    //Llenar enfermedades en COMBOBOX
    public void LLenarComboBoxEnfermedades() {
        insert_enfermedad inser = new insert_enfermedad();
        List<enfermedades> com = inser.ListEnfermedad();

        for (int i = 0; i < com.size(); i++) {
            comboenfermedadficha.addItem(com.get(i).getNombre_enfermedad());
        }
    }

    //Cargar enfermedades en JLIST
    ArrayList<enfermedades> Listaenfermedades = new ArrayList<>();

    public void CargarEnfermedadesJlist() {
        enfermedades mi_enfermedad = new enfermedades();

        if (comboenfermedadficha.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una enfermedad");
        } else {

            DefaultListModel modeloListEnfermedad;
            modeloListEnfermedad = new DefaultListModel();
            JListEnfermedades.setModel(modeloListEnfermedad);

            String enferAux;
            enferAux = comboenfermedadficha.getSelectedItem().toString();
            mi_enfermedad.setNombre_enfermedad(enferAux);

            Listaenfermedades.add(mi_enfermedad);

            for (int i = 0; i < Listaenfermedades.size(); i++) {

                modeloListEnfermedad.addElement(Listaenfermedades.get(i).getNombre_enfermedad());
                comboenfermedadficha.setSelectedIndex(0);
            }

        }
    }

    //Llenar alergias
    public void LLenarComboBoxAlergias() {
        Insert_alergias inser = new Insert_alergias();
        List<alergias> com = inser.ListaAlergias();

        for (int i = 0; i < com.size(); i++) {
            comboalergiaficha.addItem(com.get(i).getNombre_alergia());
        }
    }

    //Cargar alergias en JLIST
    ArrayList<alergias> Listaalergias = new ArrayList<>();

    public void CargarAlergiasJlist() {
        alergias mi_alergia = new alergias();

        if (comboalergiaficha.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una alergia");
        } else {

            DefaultListModel modeloListAlergia;
            modeloListAlergia = new DefaultListModel();
            JListAlergias.setModel(modeloListAlergia);

            String alerAux;
            alerAux = comboalergiaficha.getSelectedItem().toString();
            mi_alergia.setNombre_alergia(alerAux);

            Listaalergias.add(mi_alergia);

            for (int i = 0; i < Listaalergias.size(); i++) {

                modeloListAlergia.addElement(Listaalergias.get(i).getNombre_alergia());
                comboalergiaficha.setSelectedIndex(0);
            }

        }
    }

    //Cargar Datos del Paciente
    public void buscar_paciente() {
        String cedula = txtcedulafm.getText();
        var pacientefiltro = new ArrayList<paciente>();
        inser.ListaPaciente().forEach((e) -> {
            if (e.getCedula().equals(cedula)) {
                pacientefiltro.add(e);
            }
        });
        if (pacientefiltro.size() != 0) {

            List<paciente> com = inser.ListaPaciente();
            com.stream().forEach(p -> {
                txtcodigopaciente.setText(p.getCodigo().toString());
                txtnombrefm.setText(p.getPri_nomb().toString());
                txtsegundonombrefm.setText(p.getSeg_nombre().toString());
                txtapellidofm.setText(p.getPri_nomb().toString());
                txtsegundoapellidofm.setText(p.getSeg_apelli().toString());

                txtcorreofm.setText(p.getCorreo().toString());
                txtdireccionfm.setText(p.getDireccion());
                txttelefonofm.setText(p.getTelefono());
                if (p.getGenero().equalsIgnoreCase("hombre")) {
                    masculinoficha.setSelected(true);
                }
                if (p.getGenero().equalsIgnoreCase("mujer")) {
                    femeninoficha.setSelected(true);
                }

                if (p.getSeguro().equalsIgnoreCase("si")) {
                    CheckBoxSeguro.setSelected(true);
                } else {
                    CheckBoxSeguro.setSelected(false);
                }

                txtFechaNacimiento.setText(p.getFecha_Nacimiento());

                txtTipoSangre.setText(p.getTipo_sangre());

            });

        } else {
            JOptionPane.showMessageDialog(this, "El paciente no existe en la base de datos");
            LimpiarCampos();
        }
    }

    //Bloaquear Campos de texto
    public void BloquearCampos() {
        txtcodigoficha.setEditable(false);
        txtcodigopaciente.setEditable(false);
        txtnombrefm.setEditable(false);
        txtsegundonombrefm.setEditable(false);
        txtapellidofm.setEditable(false);
        txtsegundoapellidofm.setEditable(false);
        txtcorreofm.setEditable(false);
        txtdireccionfm.setEditable(false);
        txttelefonofm.setEditable(false);
        txtFechaNacimiento.setEditable(false);
        txtTipoSangre.setEditable(false);
        CheckBoxSeguro.setEnabled(false);
        masculinoficha.setEnabled(false);
        femeninoficha.setEnabled(false);

    }

    //Limpiar Campo de Texto
    public void LimpiarCampos() {
        
        txtcedulafm.setText("");
        txtcodigoficha.setText("");
        txtcodigopaciente.setText("");
        txtnombrefm.setText("");
        txtsegundonombrefm.setText("");
        txtapellidofm.setText("");
        txtsegundoapellidofm.setText("");
        txtcorreofm.setText("");
        txtdireccionfm.setText("");
        txttelefonofm.setText("");
        txtFechaNacimiento.setText("");
        txtTipoSangre.setText("");
        CheckBoxSeguro.setSelected(false);
        masculinoficha.setSelected(false);
        femeninoficha.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaMedica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton CargarAlergias;
    private javax.swing.JButton CargarEnfermedades;
    private javax.swing.JCheckBox CheckBoxSeguro;
    private javax.swing.JList<String> JListAlergias;
    private javax.swing.JList<String> JListEnfermedades;
    private javax.swing.JComboBox<String> comboalergiaficha;
    private javax.swing.JComboBox<String> comboenfermedadficha;
    private javax.swing.JRadioButton femeninoficha;
    private javax.swing.ButtonGroup gruposexoficha;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton masculinoficha;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtTipoSangre;
    private javax.swing.JTextField txtapellidofm;
    private javax.swing.JTextField txtcedulafm;
    private javax.swing.JTextField txtcodigoficha;
    private javax.swing.JTextField txtcodigopaciente;
    private javax.swing.JTextField txtcorreofm;
    private javax.swing.JTextField txtdireccionfm;
    private javax.swing.JTextField txtnombrefm;
    private javax.swing.JTextArea txtobservacionesficha;
    private javax.swing.JTextField txtsegundoapellidofm;
    private javax.swing.JTextField txtsegundonombrefm;
    private javax.swing.JTextField txttelefonofm;
    // End of variables declaration//GEN-END:variables
}
