package ventanas;

import clases.alergias;
import conexion_bada.Insert_alergias;
import clases.enfermedades;
import clases.enfermera;
import conexion_bada.insert_enfermedad;
import conexion_bada.insert_ficha_medica;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

////////////////
import clases.paciente;
import clases.FichaAlergia;
import clases.FichaEnfermedad;
import clases.validaciones;
import conexion_bada.Conexion;
//import clases.FichaMedica;
import conexion_bada.Insert;
import conexion_bada.Insert_Persona;
import conexion_bada.Insert_administrador;
import conexion_bada.Insert_enfermera;
import conexion_bada.insert_ficha_enfermedad;
import conexion_bada.insert_ficha_alergia;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class FichaMedica extends javax.swing.JFrame {

    Insert inser = new Insert();
    Insert_enfermera inserEnfermera = new Insert_enfermera();
    insert_ficha_medica inserficha = new insert_ficha_medica();
    insert_ficha_alergia inserfichaalergia = new insert_ficha_alergia();
    insert_ficha_enfermedad inserfichaenfermedad = new insert_ficha_enfermedad();

    insert_enfermedad Enfermedad = new insert_enfermedad();
    List<enfermedades> Emfer = Enfermedad.ListEnfermedad();

    Insert_alergias inserAlergias = new Insert_alergias();
    List<alergias> Aler = inserAlergias.ListaAlergias();

    DefaultListModel modeloListAlergia;
    DefaultListModel modeloListEnfermedad;
    Conexion mi_cone = new Conexion();

    ArrayList<enfermedades> Listaenfermedades = new ArrayList<>();
    ArrayList<alergias> Listaalergias = new ArrayList<>();

    ArrayList<enfermedades> ListaenfermedadesRESP = new ArrayList<>();
    ArrayList<alergias> ListaalergiasRESP = new ArrayList<>();
    boolean modificar = false, guardar = false;

    public FichaMedica() {
        initComponents();
        this.setLocationRelativeTo(null);
        guardar = true;
        btGuardarCambios.setVisible(false);
        off.setVisible(false);
        on.setVisible(false);
        MODIFICAR.setVisible(false);
        LLenarComboBoxAlergias();
        LLenarComboBoxEnfermedades();
        BloquearCampos();
        cargarcod();
    }

    public FichaMedica(int codigo_paciente) {
        initComponents();
        this.setLocationRelativeTo(null);
        guardar = false;
        LLenarComboBoxAlergias();
        LLenarComboBoxEnfermedades();
        off.setSelected(true);
        btGuardarCambios.setVisible(false);
        desabilitarParaVer();
        llenar_ficha(codigo_paciente);
        BloquearCampos();
        GuardarFicha.setVisible(false);
        cargarlistaAlergiasmodificar();
        cargarlistaEnfermedadesmodificar();
    }

//    public FichaMedica(String cedula_paciente) {
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruposexoficha = new javax.swing.ButtonGroup();
        cargarPaciente = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaPaciente = new javax.swing.JTable();
        BtBuscarPaciente = new javax.swing.JButton();
        text_buscar = new javax.swing.JTextField();
        cargarP = new javax.swing.JButton();
        cargarEnfermera = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaEnfermera = new javax.swing.JTable();
        BtBuscarenfermera = new javax.swing.JButton();
        text_buscare = new javax.swing.JTextField();
        cargarP1 = new javax.swing.JButton();
        EstadoModi = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcodigoficha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcodigopaciente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtcedulafm = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtcorreofm = new javax.swing.JTextField();
        txtdireccionfm = new javax.swing.JTextField();
        txttelefonofm = new javax.swing.JTextField();
        comboenfermedadficha = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        comboalergiaficha = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtobservacionesficha = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        fecharegistro = new com.toedter.calendar.JDateChooser();
        CheckBoxSeguro = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        GuardarFicha = new javax.swing.JButton();
        txtTipoSangre = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JListAlergias = new javax.swing.JList<>();
        CargarAlergias = new javax.swing.JButton();
        CargarEnfermedades = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JListEnfermedades = new javax.swing.JList<>();
        masculinoficha = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        femeninoficha = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtenfermeraacargo = new javax.swing.JTextField();
        buscarenfermera = new javax.swing.JButton();
        txtnombresapellidos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        RegresarCancelar = new javax.swing.JButton();
        btGuardarCambios = new javax.swing.JButton();
        EliminarEnfermedades = new javax.swing.JButton();
        EliminarAlergias = new javax.swing.JButton();
        on = new javax.swing.JRadioButton();
        off = new javax.swing.JRadioButton();
        MODIFICAR = new javax.swing.JLabel();

        cargarPaciente.setResizable(false);

        TablaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "CEDULA", "NOMBRES", "APELLIDOS"
            }
        ));
        TablaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaPacienteMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(TablaPaciente);

        BtBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        BtBuscarPaciente.setToolTipText("BUSCAR PACIENTE");
        BtBuscarPaciente.setBorder(null);
        BtBuscarPaciente.setOpaque(false);
        BtBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarPacienteActionPerformed(evt);
            }
        });

        text_buscar.setText("Buscar...");
        text_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_buscarMousePressed(evt);
            }
        });
        text_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_buscarActionPerformed(evt);
            }
        });

        cargarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carga-de-archivos.png"))); // NOI18N
        cargarP.setToolTipText("CARGAR CODIGO");
        cargarP.setBorder(null);
        cargarP.setOpaque(false);
        cargarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cargarPacienteLayout = new javax.swing.GroupLayout(cargarPaciente.getContentPane());
        cargarPaciente.getContentPane().setLayout(cargarPacienteLayout);
        cargarPacienteLayout.setHorizontalGroup(
            cargarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cargarPacienteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(text_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cargarP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(cargarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cargarPacienteLayout.setVerticalGroup(
            cargarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargarPacienteLayout.createSequentialGroup()
                .addGroup(cargarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cargarPacienteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(text_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargarPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtBuscarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargarPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cargarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cargarEnfermera.setResizable(false);

        TablaEnfermera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "CEDULA", "NOMBRES", "APELLIDOS"
            }
        ));
        TablaEnfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaEnfermeraMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(TablaEnfermera);

        BtBuscarenfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        BtBuscarenfermera.setToolTipText("BUSCAR PACIENTE");
        BtBuscarenfermera.setBorder(null);
        BtBuscarenfermera.setOpaque(false);
        BtBuscarenfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarenfermeraActionPerformed(evt);
            }
        });

        text_buscare.setText("Buscar...");
        text_buscare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_buscareMousePressed(evt);
            }
        });
        text_buscare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_buscareActionPerformed(evt);
            }
        });

        cargarP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carga-de-archivos.png"))); // NOI18N
        cargarP1.setToolTipText("CARGAR CODIGO");
        cargarP1.setBorder(null);
        cargarP1.setOpaque(false);
        cargarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cargarEnfermeraLayout = new javax.swing.GroupLayout(cargarEnfermera.getContentPane());
        cargarEnfermera.getContentPane().setLayout(cargarEnfermeraLayout);
        cargarEnfermeraLayout.setHorizontalGroup(
            cargarEnfermeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cargarEnfermeraLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(cargarEnfermeraLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(text_buscare, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtBuscarenfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cargarP1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        cargarEnfermeraLayout.setVerticalGroup(
            cargarEnfermeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargarEnfermeraLayout.createSequentialGroup()
                .addGroup(cargarEnfermeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cargarEnfermeraLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(text_buscare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargarEnfermeraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtBuscarenfermera, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargarEnfermeraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cargarP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel2.setText("Codigo de Ficha:");

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DATOS PERSONALES");
        jLabel8.setToolTipText("");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FICHA MEDICA");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        txtcodigoficha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodigoficha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigofichaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel5.setText("Apellidos:");

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel3.setText("Codigo de Paciente:");

        txtcodigopaciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodigopaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigopacienteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel4.setText("Nombres:");

        txt_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombresActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel9.setText("Cedula:");

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel10.setText("Correo Electronico:");

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel11.setText("Telefono:");

        jLabel13.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel13.setText("Direccion:");

        jLabel14.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel14.setText("Fecha de Nacimiento:");

        jLabel15.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel15.setText("Tipo de Sangre:");

        jLabel16.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ANTECEDENTES MEDICOS ");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        jLabel17.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel17.setText("ENFERMEDADES:");

        comboenfermedadficha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));

        jLabel19.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel19.setText("ALERGIAS:");

        comboalergiaficha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));

        jLabel20.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("OBSERVACIONES");
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        txtobservacionesficha.setColumns(20);
        txtobservacionesficha.setRows(5);
        jScrollPane1.setViewportView(txtobservacionesficha);

        jLabel21.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel21.setText("Fecha de registro:");

        jLabel22.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel22.setText("Seguro Medico:");

        CheckBoxSeguro.setBackground(new java.awt.Color(204, 204, 204));
        CheckBoxSeguro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBoxSeguro.setText("SI");
        CheckBoxSeguro.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        CheckBoxSeguro.setOpaque(false);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/medical-history.png"))); // NOI18N

        GuardarFicha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GuardarFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salvar (1).png"))); // NOI18N
        GuardarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarFichaActionPerformed(evt);
            }
        });

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        Buscar.setToolTipText("buscar paciente");
        Buscar.setBorder(null);
        Buscar.setOpaque(false);
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(JListAlergias);

        CargarAlergias.setText("Cargar");
        CargarAlergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarAlergiasActionPerformed(evt);
            }
        });

        CargarEnfermedades.setText("Cargar");
        CargarEnfermedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarEnfermedadesActionPerformed(evt);
            }
        });

        JListEnfermedades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JListEnfermedadesKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(JListEnfermedades);

        masculinoficha.setBackground(new java.awt.Color(204, 204, 204));
        masculinoficha.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        masculinoficha.setText("M");
        masculinoficha.setOpaque(false);

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel12.setText("Sexo:");

        femeninoficha.setBackground(new java.awt.Color(204, 204, 204));
        femeninoficha.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        femeninoficha.setText("F");
        femeninoficha.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel6.setText("Enfermera acargo:");

        txtenfermeraacargo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtenfermeraacargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenfermeraacargoActionPerformed(evt);
            }
        });

        buscarenfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_1.png"))); // NOI18N
        buscarenfermera.setToolTipText("buscar paciente");
        buscarenfermera.setBorder(null);
        buscarenfermera.setOpaque(false);
        buscarenfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarenfermeraActionPerformed(evt);
            }
        });

        txtnombresapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombresapellidosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel7.setText("Codigo enfermera:");

        RegresarCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegresarCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        RegresarCancelar.setToolTipText("REGRESAR");
        RegresarCancelar.setBorder(null);
        RegresarCancelar.setOpaque(false);
        RegresarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarCancelarActionPerformed(evt);
            }
        });

        btGuardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar-documento.png"))); // NOI18N
        btGuardarCambios.setToolTipText("MODIFICAR");
        btGuardarCambios.setBorder(null);
        btGuardarCambios.setBorderPainted(false);
        btGuardarCambios.setOpaque(false);
        btGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarCambiosActionPerformed(evt);
            }
        });

        EliminarEnfermedades.setText("Eliminar");
        EliminarEnfermedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEnfermedadesActionPerformed(evt);
            }
        });

        EliminarAlergias.setText("Eliminar");
        EliminarAlergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarAlergiasActionPerformed(evt);
            }
        });

        EstadoModi.add(on);
        on.setText("Habilitado");
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });

        EstadoModi.add(off);
        off.setText("Deshabilitado");
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });

        MODIFICAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MODIFICAR.setText("MODIFICAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttelefonofm, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcedulafm, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Buscar)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(CheckBoxSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6)
                                .addComponent(masculinoficha)
                                .addGap(18, 18, 18)
                                .addComponent(femeninoficha)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtdireccionfm, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcorreofm, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboenfermedadficha, 0, 160, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CargarEnfermedades)
                                .addGap(175, 175, 175)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EliminarEnfermedades))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(comboalergiaficha, 0, 160, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CargarAlergias)
                            .addComponent(EliminarAlergias)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtcodigoficha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtcodigopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fecharegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtnombresapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtenfermeraacargo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buscarenfermera))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(453, 453, 453)
                .addComponent(GuardarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGuardarCambios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegresarCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(on)
                        .addGap(18, 18, 18)
                        .addComponent(off)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(MODIFICAR)
                        .addGap(113, 113, 113))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcodigoficha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(fecharegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcodigopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtenfermeraacargo)
                            .addComponent(txtnombresapellidos)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buscarenfermera)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CheckBoxSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel12)
                        .addComponent(masculinoficha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(femeninoficha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(txtTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtcedulafm, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Buscar))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcorreofm, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefonofm, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(txtdireccionfm, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(comboenfermedadficha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CargarEnfermedades)
                    .addComponent(jLabel19)
                    .addComponent(comboalergiaficha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CargarAlergias))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EliminarEnfermedades)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EliminarAlergias, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(19, 19, 19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(MODIFICAR)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(off)
                                                .addComponent(on)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(RegresarCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(GuardarFicha))))
                        .addComponent(btGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigofichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigofichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigofichaActionPerformed

    private void txtcodigopacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigopacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigopacienteActionPerformed

    private void txt_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombresActionPerformed

    private void CargarAlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarAlergiasActionPerformed
        CargarAlergiasJlist();
    }//GEN-LAST:event_CargarAlergiasActionPerformed

    private void CargarEnfermedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarEnfermedadesActionPerformed
        CargarEnfermedadesJlist();
//        verlistaemfer();
    }//GEN-LAST:event_CargarEnfermedadesActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        cargarPaciente.setSize(494, 258);
        cargarTablaP();
        cargarPaciente.setVisible(true);
        cargarPaciente.setLocationRelativeTo(Buscar);
    }//GEN-LAST:event_BuscarActionPerformed

    private void txtenfermeraacargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenfermeraacargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenfermeraacargoActionPerformed

    private void buscarenfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarenfermeraActionPerformed
        cargarEnfermera.setSize(494, 258);
        cargarTablaE();
        cargarEnfermera.setVisible(true);
        cargarEnfermera.setLocationRelativeTo(buscarenfermera);
    }//GEN-LAST:event_buscarenfermeraActionPerformed

    private void TablaPacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPacienteMousePressed

    }//GEN-LAST:event_TablaPacienteMousePressed

    private void BtBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarPacienteActionPerformed

        if (!text_buscar.getText().isEmpty()) {
            buscar_paciente();
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese la cedula del paciente");
        }
    }//GEN-LAST:event_BtBuscarPacienteActionPerformed

    private void text_buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_buscarMousePressed

        text_buscar.setText("");
        text_buscar.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_buscarMousePressed

    private void text_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_buscarActionPerformed

    private void cargarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarPActionPerformed
        cargar_codigo_paci();
    }//GEN-LAST:event_cargarPActionPerformed

    private void TablaEnfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEnfermeraMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaEnfermeraMousePressed

    private void BtBuscarenfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarenfermeraActionPerformed
        if (!text_buscare.getText().isEmpty()) {
            buscar_enfermera();
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese la cedula de la enfermera");
        }
    }//GEN-LAST:event_BtBuscarenfermeraActionPerformed

    private void text_buscareMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_buscareMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_buscareMousePressed

    private void text_buscareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_buscareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_buscareActionPerformed

    private void cargarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarP1ActionPerformed
        cargar_codigo_enfermera();
    }//GEN-LAST:event_cargarP1ActionPerformed

    private void txtnombresapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombresapellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombresapellidosActionPerformed

    private void GuardarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarFichaActionPerformed
        try {
            RegistrarFicha();
        } catch (SQLException ex) {
            Logger.getLogger(FichaMedica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GuardarFichaActionPerformed

    private void RegresarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarCancelarActionPerformed

        new crud_FichaMedica().setVisible(true);
        this.dispose();
        System.out.println(guardar);
        comprobarlista();
        if (guardar == false) {
            GuardarMODIsinGuardar();
        }

//        }

    }//GEN-LAST:event_RegresarCancelarActionPerformed

    private void btGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarCambiosActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "¿Seguro que desea modificarlo?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            modificar_ficha();
            guardar = true;
            off.setSelected(true);
        }
    }//GEN-LAST:event_btGuardarCambiosActionPerformed

    private void EliminarEnfermedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEnfermedadesActionPerformed
        if (JListEnfermedades.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una enfermedad");
        } else {
            ElimarEnfermedadesJlist();
        }
//        verlistaemfer();
    }//GEN-LAST:event_EliminarEnfermedadesActionPerformed

    private void EliminarAlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAlergiasActionPerformed
        if (JListAlergias.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una alergia");
        } else {
            ElimarAlergiaJlist();
        }
    }//GEN-LAST:event_EliminarAlergiasActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
        habilitarModificar();
    }//GEN-LAST:event_onActionPerformed

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
        desabilitarParaVer();
    }//GEN-LAST:event_offActionPerformed

    private void JListEnfermedadesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JListEnfermedadesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JListEnfermedadesKeyPressed

    public void modificar_ficha() {

        Buscar.setEnabled(true);
        buscarenfermera.setEnabled(true);
        modificar = true;

        GuardarEnferAlergMODI();
        mi_cone.InsertUpdateDeleteAcciones("UPDATE ficha SET ficha_paci_codigo=" + Integer.parseInt(txtcodigopaciente.getText()) + ",ficha_enfermera_acargo=" + Integer.parseInt(txtenfermeraacargo.getText()) + ",ficha_observaciones='" + txtobservacionesficha.getText() + "' WHERE ficha_codigo=" + Integer.parseInt(txtcodigoficha.getText()) + ";");

        modificar = false;
        desabilitarParaVer();

    }

    public void comprobarlista() {
        System.out.println("ENFERMEDADES");
        for (int i = 0; i < Listaenfermedades.size(); i++) {

            System.out.println(Listaenfermedades.get(i).getCodigo_enfermedad());
        }

        System.out.println("/n ALERGIAS");
        for (int i = 0; i < Listaalergias.size(); i++) {

            System.out.println(Listaalergias.get(i).getNombre_alergia());
        }
    }

    public void RegistrarFicha() throws SQLException {
        modificar = false;
        try {
            if (validaciones()) {
                if (inserficha.validarduplicado(Integer.parseInt(txtcodigopaciente.getText()))) {
                    inserficha.setCodigo_enfermera(Integer.parseInt(txtenfermeraacargo.getText()));
                    inserficha.setCodigo_paciente(Integer.parseInt(txtcodigopaciente.getText()));
                    inserficha.setObservaciones(txtobservacionesficha.getText());
                    inserficha.InsertarFichaMedica();

                    GuardarEnferAlerg();

                    System.out.println("Conexion Exitosa");
                    Limpiar();
                    Limpiar2();
                    cargarcod();

                } else {
                    JOptionPane.showMessageDialog(this, "LA FICHA DEL PACIENTE YA EXISTE");
                    Limpiar();
                }
            }
        } catch (NullPointerException n) {

        }

    }

    public void GuardarEnferAlergMODI() {
        for (int i = 0; i < Listaenfermedades.size(); i++) {
//                System.out.println("Enfermedar=" + Listaenfermedades.get(i).getNombre_enfermedad());
            inserfichaenfermedad.setCodigo_ficha(Integer.parseInt(txtcodigoficha.getText()));
            inserfichaenfermedad.setCodigo_enfermedad(Listaenfermedades.get(i).getCodigo_enfermedad());
            inserfichaenfermedad.InsertarFichaEnfermedad();
        }
        for (int i = 0; i < Listaalergias.size(); i++) {
            inserfichaalergia.setCodigo_ficha(Integer.parseInt(txtcodigoficha.getText()));
            inserfichaalergia.setCodigo_alergia(Listaalergias.get(i).getCodigo_alergia());
            inserfichaalergia.InsertarFichaAlergia();
        }
    }
    
        public void GuardarMODIsinGuardar() {
        for (int i = 0; i < ListaenfermedadesRESP.size(); i++) {
//                System.out.println("Enfermedar=" + Listaenfermedades.get(i).getNombre_enfermedad());
            inserfichaenfermedad.setCodigo_ficha(Integer.parseInt(txtcodigoficha.getText()));
            inserfichaenfermedad.setCodigo_enfermedad(ListaenfermedadesRESP.get(i).getCodigo_enfermedad());
            inserfichaenfermedad.InsertarFichaEnfermedad();
        }
        for (int i = 0; i < ListaalergiasRESP.size(); i++) {
            inserfichaalergia.setCodigo_ficha(Integer.parseInt(txtcodigoficha.getText()));
            inserfichaalergia.setCodigo_alergia(ListaalergiasRESP.get(i).getCodigo_alergia());
            inserfichaalergia.InsertarFichaAlergia();
        }
    }

    public void GuardarEnferAlerg() {
        for (int i = 0; i < Listaenfermedades.size(); i++) {
            inserfichaenfermedad.setCodigo_ficha(inserficha.obtenerFicha());
            inserfichaenfermedad.setCodigo_enfermedad(Listaenfermedades.get(i).getCodigo_enfermedad());
            inserfichaenfermedad.InsertarFichaEnfermedad();
        }

        for (int i = 0; i < Listaalergias.size(); i++) {
            inserfichaalergia.setCodigo_ficha(inserficha.obtenerFicha());
            inserfichaalergia.setCodigo_alergia(Listaalergias.get(i).getCodigo_alergia());
            inserfichaalergia.InsertarFichaAlergia();
        }

    }

    public void desabilitarParaVer() {
        txtnombresapellidos.setEditable(false);
        txtobservacionesficha.setEditable(false);
        comboalergiaficha.setEnabled(false);
        comboenfermedadficha.setEnabled(false);
        CargarEnfermedades.setVisible(false);
        CargarAlergias.setVisible(false);
        EliminarAlergias.setVisible(false);
        EliminarEnfermedades.setVisible(false);
        buscarenfermera.setVisible(false);
        Buscar.setVisible(false);
        btGuardarCambios.setVisible(false);
    }

    public void habilitarModificar() {
//        txtnombresapellidos.setEditable(true);
        txtobservacionesficha.setEditable(true);
        comboalergiaficha.setEnabled(true);
        comboenfermedadficha.setEnabled(true);
        CargarEnfermedades.setVisible(true);
        CargarAlergias.setVisible(true);
        buscarenfermera.setVisible(true);
        Buscar.setVisible(true);
        GuardarFicha.setVisible(false);
        btGuardarCambios.setVisible(true);
        EliminarEnfermedades.setVisible(true);
        EliminarAlergias.setVisible(true);
    }

    public void llenar_ficha(int codigoP) {
//        Limpiar2();
        List<clases.claseFichaMedica> com = inserficha.ListaFichaMedica();
        com.stream().forEach(f -> {
            if (codigoP == f.getCodigo_paciente()) {
                txtenfermeraacargo.setText(String.valueOf(f.getCodigo_enfermera()));
                txtcodigoficha.setText(String.valueOf(f.getCodigo_ficha_medica()));
                txtobservacionesficha.setText(f.getObservaciones());
                txtcodigopaciente.setText(String.valueOf(f.getCodigo_paciente()));
                SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
                Date fecha = null;
                try {
                    fecha = formatofecha.parse(f.getFecha_de_ingreso());
                } catch (ParseException ex) {
                    Logger.getLogger(Agregar_administrador.class.getName()).log(Level.SEVERE, null, ex);
                }
                fecharegistro.setDate(fecha);
                txtcedulafm.setText(f.getCedula());
                txt_nombres.setText(f.getPri_nomb() + "  " + f.getSeg_nombre());
                txt_apellidos.setText(f.getPrim_apell() + "  " + f.getSeg_apelli());
                txttelefonofm.setText(f.getTelefono());
                txtdireccionfm.setText(f.getDireccion());
                txtcorreofm.setText(f.getCorreo());
                txtFechaNacimiento.setText(f.getFecha_Nacimiento());
                if (f.getGenero().equalsIgnoreCase("hombre")) {
                    masculinoficha.setSelected(true);
                }
                if (f.getGenero().equalsIgnoreCase("mujer")) {
                    femeninoficha.setSelected(true);
                }
                txtTipoSangre.setText(f.getTipo_sangre());
                if (f.getSeguro().equalsIgnoreCase("si")) {
                    CheckBoxSeguro.setSelected(true);
                } else {
                    CheckBoxSeguro.setSelected(false);
                }
                List<enfermera> enferA = inserEnfermera.ListaEnfermeraAcargo(f.getCodigo_enfermera());
                enferA.stream().forEach(e -> {
                    txtnombresapellidos.setText(e.getPri_nomb() + "  " + e.getSeg_nombre() + "  " + e.getPrim_apell() + "  " + e.getSeg_apelli());
                });
                modeloListEnfermedad = new DefaultListModel();
                List<enfermedades> enfer = inserfichaenfermedad.ListaEnfermedades(f.getCodigo_ficha_medica());
                enfer.stream().forEach(enfe -> {

                    JListEnfermedades.setModel(modeloListEnfermedad);
                    modeloListEnfermedad.addElement(enfe.getNombre_enfermedad());
                });
                modeloListAlergia = new DefaultListModel();
                List<alergias> aler = inserfichaalergia.Listaalergias(f.getCodigo_ficha_medica());
                aler.stream().forEach(ale -> {
//                    
                    JListAlergias.setModel(modeloListAlergia);
                    modeloListAlergia.addElement(ale.getNombre_alergia());
                });

            }
        });

    }

    public void cargarcod() {
        txtcodigoficha.setEnabled(false);
        txtcodigoficha.setText(String.valueOf(inserficha.cargarcodigo()));
    }

    //Llenar enfermedades en COMBOBOX
    public void LLenarComboBoxEnfermedades() {
        for (int i = 0; i < Emfer.size(); i++) {
            comboenfermedadficha.addItem(Emfer.get(i).getNombre_enfermedad());
        }
    }

    //Cargar enfermedades en JLIST
    public void cargarlistaEnfermedadesmodificar() {
        int codigo = Integer.valueOf(txtcodigoficha.getText());
        enfermedades mi_enfermedad = new enfermedades();
        for (int i = 0; i < inserfichaenfermedad.ListaEnfermedades(Integer.parseInt(txtcodigoficha.getText())).size(); i++) {
            mi_enfermedad.setCodigo_enfermedad(inserfichaenfermedad.ListaEnfermedades(Integer.parseInt(txtcodigoficha.getText())).get(i).getCodigo_enfermedad());
            mi_enfermedad.setNombre_enfermedad(inserfichaenfermedad.ListaEnfermedades(Integer.parseInt(txtcodigoficha.getText())).get(i).getNombre_enfermedad());
            ListaenfermedadesRESP.add(mi_enfermedad);
            Listaenfermedades.add(mi_enfermedad);
        }

        mi_cone.InsertUpdateDeleteAcciones("DELETE FROM ficha_enfermedad where fe_codigo_ficha=" + codigo + "");

    }

    public void cargarlistaAlergiasmodificar() {
        int codigo = Integer.valueOf(txtcodigoficha.getText());
        alergias mi_alergia = new alergias();
//        Listaalergias = (ArrayList<alergias>) inserfichaalergia.Listaalergias(Integer.parseInt(txtcodigoficha.getText()));
        for (int i = 0; i < inserfichaalergia.Listaalergias(Integer.parseInt(txtcodigoficha.getText())).size(); i++) {
            mi_alergia.setCodigo_alergia(inserfichaalergia.Listaalergias(Integer.parseInt(txtcodigoficha.getText())).get(i).getCodigo_alergia());
            mi_alergia.setNombre_alergia(inserfichaalergia.Listaalergias(Integer.parseInt(txtcodigoficha.getText())).get(i).getNombre_alergia());
            ListaalergiasRESP.add(mi_alergia);
            Listaalergias.add(mi_alergia);
        }
        mi_cone.InsertUpdateDeleteAcciones("DELETE FROM ficha_alergia where fa_codigo_ficha=" + codigo + "");

    }

    public void CargarEnfermedadesJlist() {
        enfermedades mi_enfermedad = new enfermedades();
        boolean rep = false;
        if (comboenfermedadficha.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado un medicamento");
        } else {


            modeloListEnfermedad = new DefaultListModel();
            JListEnfermedades.setModel(modeloListEnfermedad);

            String enferAux;
            enferAux = comboenfermedadficha.getSelectedItem().toString();

            mi_enfermedad.setNombre_enfermedad(enferAux);
            mi_enfermedad.setCodigo_enfermedad(inserfichaenfermedad.cargarcodigoEnfermedad(enferAux));
            if (Listaenfermedades.size() != 0) {
                for (int i = 0; i < Listaenfermedades.size(); i++) {
                    rep = false;
                    if (enferAux.equalsIgnoreCase(Listaenfermedades.get(i).getNombre_enfermedad())) {
//                        System.out.println(enferAux + " = " + Listaenfermedades.get(i).getNombre_enfermedad());
                        rep = true;
                        i = Listaenfermedades.size();
                    }
                }
            } else {
                rep = true;
                Listaenfermedades.add(mi_enfermedad);
            }
            if (rep == false) {
                Listaenfermedades.add(mi_enfermedad);
            }

            for (int i = 0; i < Listaenfermedades.size(); i++) {

                modeloListEnfermedad.addElement(Listaenfermedades.get(i).getNombre_enfermedad());
                comboenfermedadficha.setSelectedIndex(0);
            }
        }
    }

    public void ElimarEnfermedadesJlist() {
        if (Listaenfermedades.size() != 0) {
            int indice = JListEnfermedades.getSelectedIndex();
//            System.out.println(indice);
            modeloListEnfermedad.remove(indice);
            Listaenfermedades.remove(indice);
        } else {
            cargarlistaEnfermedadesmodificar();
        }

    }

    //Llenar alergias
    public void LLenarComboBoxAlergias() {

        for (int i = 0; i < Aler.size(); i++) {
            comboalergiaficha.addItem(Aler.get(i).getNombre_alergia());
        }
    }

    //Cargar alergias en JLIST
    public void CargarAlergiasJlist() {
        alergias mi_alergia = new alergias();
        boolean rep = false;
        if (comboalergiaficha.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una alergia");
        } else {

//            DefaultListModel modeloListAlergia;
            modeloListAlergia = new DefaultListModel();
            JListAlergias.setModel(modeloListAlergia);

            String alerAux;
            alerAux = comboalergiaficha.getSelectedItem().toString();
            mi_alergia.setNombre_alergia(alerAux);
            mi_alergia.setCodigo_alergia(inserfichaalergia.cargarcodigoAlergia(alerAux));

            if (Listaalergias.size() != 0) {
                for (int i = 0; i < Listaalergias.size(); i++) {
                    rep = false;
                    if (alerAux.equalsIgnoreCase(Listaalergias.get(i).getNombre_alergia())) {
                        rep = true;
                        i = Listaalergias.size();
                    }
                }
            } else {
                rep = true;
                Listaalergias.add(mi_alergia);
            }
            if (rep == false) {
                Listaalergias.add(mi_alergia);
            }

            for (int i = 0; i < Listaalergias.size(); i++) {

                modeloListAlergia.addElement(Listaalergias.get(i).getNombre_alergia());
                comboalergiaficha.setSelectedIndex(0);
            }

        }
    }

    public void ElimarAlergiaJlist() {
        if (Listaalergias.size() != 0) {
            int indice = JListAlergias.getSelectedIndex();
//            System.out.println(indice);
            modeloListAlergia.remove(indice);
            Listaalergias.remove(indice);
        } else {
            cargarlistaAlergiasmodificar();
        }

    }

    public void buscar_paciente() {
        String cedula = text_buscar.getText();
        var pacientefiltro = new ArrayList<paciente>();
        inser.ListaPaciente().forEach((e) -> {
            if (e.getCedula().equals(cedula)) {
                pacientefiltro.add(e);
            }
        });
        if (pacientefiltro.size() != 0) {

            String matriz[][] = new String[pacientefiltro.size()][4];
            for (int j = 0; j < pacientefiltro.size(); j++) {
                matriz[j][0] = String.valueOf(pacientefiltro.get(j).getCodigo());
                matriz[j][1] = pacientefiltro.get(j).getCedula();
                matriz[j][2] = pacientefiltro.get(j).getPri_nomb() + "  " + pacientefiltro.get(j).getSeg_nombre();
                matriz[j][3] = pacientefiltro.get(j).getPrim_apell() + "  " + pacientefiltro.get(j).getSeg_apelli();;

            }
            TablaPaciente.setModel(new javax.swing.table.DefaultTableModel(
                    matriz,
                    new String[]{
                        "CODIGO", "CEDULA", "NOMBRES", "APELLIDOS"
                    }
            ));
        } else {
            JOptionPane.showMessageDialog(this, "El paciente no existe en la base de datos");
        }
    }

    public void cargarTablaP() {
        DefaultTableModel tb = (DefaultTableModel) TablaPaciente.getModel();
        tb.setNumRows(0);
        List<paciente> com = inser.ListaPaciente();
        com.stream().forEach(p -> {
            String[] cami = {String.valueOf(p.getCodigo()), p.getPri_nomb() + "  " + p.getSeg_nombre(), p.getCedula(), p.getPrim_apell() + "  " + p.getSeg_apelli()};
            tb.addRow(cami);
        });
    }

    public void cargar_codigo_paci() {
        int seleccion = TablaPaciente.getSelectedRow();

        if (seleccion == -1) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una fila");
        } else {
            int codigo = Integer.parseInt(TablaPaciente.getValueAt(seleccion, 0).toString());
            inser.ListaPaciente().forEach((p) -> {
                if (p.getCodigo() == codigo) {
//                    new Agregar_paciente(codigo).setVisible(true);
                    txtcedulafm.setText(p.getCedula());
                    txtcodigopaciente.setText(String.valueOf(p.getCodigo()));
                    txt_apellidos.setText(p.getPrim_apell() + "  " + p.getSeg_apelli());
                    txt_nombres.setText(p.getPri_nomb() + "  " + p.getSeg_nombre());
                    txtcorreofm.setText(p.getCorreo());
                    txttelefonofm.setText(p.getTelefono());
                    txtdireccionfm.setText(p.getDireccion());
                    txtFechaNacimiento.setText(p.getFecha_Nacimiento());
                    txtTipoSangre.setText(p.getTipo_sangre());
                    SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
                    Date fecha = null;
                    try {
                        fecha = formatofecha.parse(p.getFecha_de_ingreso());
                    } catch (ParseException ex) {
                        Logger.getLogger(Agregar_administrador.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    fecharegistro.setDate(fecha);
                    if (p.getGenero().equalsIgnoreCase("hombre")) {
                        masculinoficha.setSelected(true);
                    }
                    if (p.getGenero().equalsIgnoreCase("mujer")) {
                        femeninoficha.setSelected(true);
                    }

                    if (p.getSeguro().equalsIgnoreCase("si")) {
                        CheckBoxSeguro.setSelected(true);
                    } else {
                        CheckBoxSeguro.setSelected(false);
                    }
                    cargarPaciente.dispose();
                }
            });

            String cod;
            cod = TablaPaciente.getValueAt(seleccion, 0).toString();
            txtcodigopaciente.setText(cod);
//            System.out.println(cod);
            cargarPaciente.dispose();
        }
    }
////////////////////////////////////////////////////////////////////

    public void buscar_enfermera() {
        String cedula = text_buscare.getText();
        var enfermerafiltro = new ArrayList<enfermera>();
        inserEnfermera.ListaEnfermera().forEach((e) -> {
            if (e.getCedula().equals(cedula)) {
                enfermerafiltro.add(e);
            }
        });
        if (enfermerafiltro.size() != 0) {

            String matriz[][] = new String[enfermerafiltro.size()][4];
            for (int j = 0; j < enfermerafiltro.size(); j++) {
                matriz[j][0] = String.valueOf(enfermerafiltro.get(j).getCodigo());
                matriz[j][1] = enfermerafiltro.get(j).getCedula();
                matriz[j][2] = enfermerafiltro.get(j).getPri_nomb() + "  " + enfermerafiltro.get(j).getSeg_nombre();
                matriz[j][3] = enfermerafiltro.get(j).getPrim_apell() + "  " + enfermerafiltro.get(j).getSeg_apelli();;

            }
            TablaPaciente.setModel(new javax.swing.table.DefaultTableModel(
                    matriz,
                    new String[]{
                        "CODIGO", "CEDULA", "NOMBRES", "APELLIDOS"
                    }
            ));
        } else {
            JOptionPane.showMessageDialog(this, "La enfermera no existe en la base de datos");
        }
    }

    public void cargarTablaE() {
        DefaultTableModel tb = (DefaultTableModel) TablaEnfermera.getModel();
        tb.setNumRows(0);
        List<enfermera> com = inserEnfermera.ListaEnfermera();
        com.stream().forEach(p -> {
            String[] cami = {String.valueOf(p.getCodigo()), p.getCedula(), p.getPrim_apell() + "  " + p.getSeg_apelli(), p.getPri_nomb() + "  " + p.getSeg_nombre()};
            tb.addRow(cami);
        });
    }

    public void cargar_codigo_enfermera() {
        int seleccion = TablaEnfermera.getSelectedRow();

        if (seleccion == -1) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una fila");
        } else {
            int codigo = Integer.parseInt(TablaEnfermera.getValueAt(seleccion, 0).toString());
            inserEnfermera.ListaEnfermera().forEach((e) -> {
                if (e.getCodigo() == codigo) {
//                    new Agregar_paciente(codigo).setVisible(true);
                    txtenfermeraacargo.setText(String.valueOf(e.getCodigo()));
                    txtnombresapellidos.setText(e.getPri_nomb() + " " + e.getSeg_nombre() + " " + e.getPrim_apell() + " " + e.getSeg_apelli());

                    cargarEnfermera.dispose();
                }
            });

            String cod;
            cod = TablaEnfermera.getValueAt(seleccion, 0).toString();
//            System.out.println(cod);
            cargarEnfermera.dispose();
        }
    }

    //Bloaquear Campos de texto
    public void BloquearCampos() {
        txtcodigoficha.setEditable(false);
        txtcodigopaciente.setEditable(false);
        txt_apellidos.setEditable(false);
        txt_nombres.setEditable(false);
        txtcorreofm.setEditable(false);
        txtdireccionfm.setEditable(false);
        txttelefonofm.setEditable(false);
        txtFechaNacimiento.setEditable(false);
        txtTipoSangre.setEditable(false);
        CheckBoxSeguro.setEnabled(false);
        masculinoficha.setEnabled(false);
        femeninoficha.setEnabled(false);
        txtenfermeraacargo.setEditable(false);
        fecharegistro.setEnabled(false);
    }

    //Limpiar Campo de Texto
    public void Limpiar() {
        txtcedulafm.setText("");
        txtcodigoficha.setText("");
        txtcodigopaciente.setText("");
        txt_apellidos.setText("");
        txt_nombres.setText("");
        txtcorreofm.setText("");
        txtdireccionfm.setText("");
        txttelefonofm.setText("");
        txtFechaNacimiento.setText("");
        txtTipoSangre.setText("");
        CheckBoxSeguro.setSelected(false);
        masculinoficha.setSelected(false);
        femeninoficha.setSelected(false);

        txtobservacionesficha.setText("");
    }

    public void Limpiar2() {

        DefaultListModel modelo = new DefaultListModel();
        JListAlergias.setModel(modelo);
        JListEnfermedades.setModel(modelo);

        txtenfermeraacargo.setText("");
        txtnombresapellidos.setText("");
    }

    public boolean validaciones() {
        boolean validado = true;
        validaciones misvalidaciones = new validaciones();
        if (txtcedulafm.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la cedula");
        } else {
            if (!misvalidaciones.validar_cedula(txtcedulafm.getText())) {
                JOptionPane.showMessageDialog(this, "Cedula incorrecta");
                validado = false;
            }
        }
//
        if (txtcodigopaciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione un paciente");
        }

        if (txt_apellidos.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione un paciente");
        }

        if (txt_nombres.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione un paciente");
        }

        if (txtcorreofm.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione un paciente");
        }
        if (txtdireccionfm.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione un paciente");
        }
        if (txttelefonofm.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione un paciente");
        }
        if (txtFechaNacimiento.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione un paciente");
        }
        if (txtTipoSangre.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione un paciente");
        }

        if (!masculinoficha.isSelected() && !femeninoficha.isSelected()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "seleccione un genero");
        }

        if (txtenfermeraacargo.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione la enfermera acargo");
        }
        if (txtnombresapellidos.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione la enfermera acargo");
        }
        if (fecharegistro.getDate() == null) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la fecha de registro");
        }

        return validado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FichaMedica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscarPaciente;
    private javax.swing.JButton BtBuscarenfermera;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton CargarAlergias;
    private javax.swing.JButton CargarEnfermedades;
    private javax.swing.JCheckBox CheckBoxSeguro;
    private javax.swing.JButton EliminarAlergias;
    private javax.swing.JButton EliminarEnfermedades;
    private javax.swing.ButtonGroup EstadoModi;
    private javax.swing.JButton GuardarFicha;
    private javax.swing.JList<String> JListAlergias;
    private javax.swing.JList<String> JListEnfermedades;
    private javax.swing.JLabel MODIFICAR;
    private javax.swing.JButton RegresarCancelar;
    private javax.swing.JTable TablaEnfermera;
    private javax.swing.JTable TablaPaciente;
    private javax.swing.JButton btGuardarCambios;
    private javax.swing.JButton buscarenfermera;
    private javax.swing.JDialog cargarEnfermera;
    private javax.swing.JButton cargarP;
    private javax.swing.JButton cargarP1;
    private javax.swing.JDialog cargarPaciente;
    private javax.swing.JComboBox<String> comboalergiaficha;
    private javax.swing.JComboBox<String> comboenfermedadficha;
    private com.toedter.calendar.JDateChooser fecharegistro;
    private javax.swing.JRadioButton femeninoficha;
    private javax.swing.ButtonGroup gruposexoficha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton masculinoficha;
    private javax.swing.JRadioButton off;
    private javax.swing.JRadioButton on;
    private javax.swing.JTextField text_buscar;
    private javax.swing.JTextField text_buscare;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtTipoSangre;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txtcedulafm;
    private javax.swing.JTextField txtcodigoficha;
    private javax.swing.JTextField txtcodigopaciente;
    private javax.swing.JTextField txtcorreofm;
    private javax.swing.JTextField txtdireccionfm;
    private javax.swing.JTextField txtenfermeraacargo;
    private javax.swing.JTextField txtnombresapellidos;
    private javax.swing.JTextArea txtobservacionesficha;
    private javax.swing.JTextField txttelefonofm;
    // End of variables declaration//GEN-END:variables
}
