/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.doctor;
import clases.paciente;
import clases.cita_medica;
import conexion_bada.Conexion;
import conexion_bada.Insert;
import conexion_bada.Insert_ChequeoMedico;
import conexion_bada.Insert_doctor;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class listadoDeCitasDoctor extends javax.swing.JFrame {
    Conexion mi_cone = new Conexion();
    Insert_ChequeoMedico inserchequeo = new Insert_ChequeoMedico();

    /**
     * Creates new form listadoDeCitasDoctor
     */
    public listadoDeCitasDoctor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
      public void FiltrarDatosChequeoTabla() {

        String cedulaAux = txtCedula.getText();
        int codDoc = 0;

        Insert_ChequeoMedico inserchek = new Insert_ChequeoMedico();

        List<doctor> com = inserchek.ListaChequeoDoctor();

        for (int i = 0; i < com.size(); i++) {
            if (com.get(i).getCedula().equalsIgnoreCase(cedulaAux)) {

                codDoc = com.get(i).getCodigo();
                
            }
        }

        //Conocer codigo del doctor
        System.out.println("Bien codDoc: " + codDoc);

        var pacidosfiltro = new ArrayList<paciente>();
        inserchequeo.ListaChequeoPacienteDos(codDoc).forEach((e) -> {
            pacidosfiltro.add(e);
        });

        String matriz[][] = new String[pacidosfiltro.size()][6];

        for (int i = 0; i < pacidosfiltro.size(); i++) {

            matriz[i][1] = pacidosfiltro.get(i).getCedula();
            matriz[i][2] = pacidosfiltro.get(i).getPri_nomb() + " " + pacidosfiltro.get(i).getSeg_nombre();
            matriz[i][3] = pacidosfiltro.get(i).getPrim_apell() + " " + pacidosfiltro.get(i).getSeg_apelli();

        }

        var citfiltro = new ArrayList<clases.cita_medica>();
        inserchequeo.ListaChequeoDos(codDoc).forEach((e) -> {
            citfiltro.add(e);
        });

        for (int j = 0; j < citfiltro.size(); j++) {

            matriz[j][4] = citfiltro.get(j).getFecha_chequeoActual();
            matriz[j][5] = citfiltro.get(j).getHoraChequeo();
            matriz[j][0] = String.valueOf(citfiltro.get(j).getCodigo_citas());
        }

        TablaChequeosDoctor.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Codigo de chequeo", "Cédula del paciente", "Nombres del paciente", "Apellidos del paciente", "Fecha del chequeo médico", "Hora del chequeo médico"
                }
        ));
    }
      public void ChequeoRealizado() {

        int fila = TablaChequeosDoctor.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una fila");
        } else {

            int response = JOptionPane.showConfirmDialog(this, "Los chequeos realizados se perderan y ya no podra vizualizarlos\n¿Aceptar?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {

                String codigoCita;
                codigoCita = TablaChequeosDoctor.getValueAt(fila, 0).toString();
                try {
                    mi_cone.InsertUpdateDeleteAcciones("UPDATE cita SET cita_check = 'No' Where cita_codigo = '" + codigoCita + "'");
                    JOptionPane.showMessageDialog(null, "La chequeo se ha vaciado de su lista con éxito");
                    FiltrarDatosChequeoTabla();
                } catch (Exception e) {
                    //System.out.println(e.toString());
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaChequeosDoctor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ChequeoRealizado = new javax.swing.JButton();
        boton_regresar_menu_doctor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 232, 158));

        TablaChequeosDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Chequeo", "Cedula Paciente", "Nombres Paciente", "Apellido Paciente", "Fecha Chequeo", "Hora Chequeo"
            }
        ));
        jScrollPane1.setViewportView(TablaChequeosDoctor);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Listado de Chequeos Medicos del Paciente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Digite su número de cédula:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hogar_de_los_ancianos__1_-removebg-preview (2).png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        jButton1.setToolTipText("BUSCAR CITAS PENDIENTES");
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ChequeoRealizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prueba.png"))); // NOI18N
        ChequeoRealizado.setToolTipText("CHEQUEO ATENDIDO");
        ChequeoRealizado.setBorder(null);
        ChequeoRealizado.setOpaque(false);
        ChequeoRealizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChequeoRealizadoActionPerformed(evt);
            }
        });

        boton_regresar_menu_doctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        boton_regresar_menu_doctor.setToolTipText("REGRESAR MENU DOCTOR");
        boton_regresar_menu_doctor.setBorder(null);
        boton_regresar_menu_doctor.setOpaque(false);
        boton_regresar_menu_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_regresar_menu_doctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 264, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton1)
                                .addGap(70, 70, 70)
                                .addComponent(ChequeoRealizado)
                                .addGap(55, 55, 55)
                                .addComponent(boton_regresar_menu_doctor)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ChequeoRealizado)
                    .addComponent(boton_regresar_menu_doctor)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FiltrarDatosChequeoTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ChequeoRealizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChequeoRealizadoActionPerformed
        // TODO add your handling code here:
        ChequeoRealizado();
    }//GEN-LAST:event_ChequeoRealizadoActionPerformed

    private void boton_regresar_menu_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_regresar_menu_doctorActionPerformed
        // TODO add your handling code here:
         acceso_doctor acdoctor = new acceso_doctor();
        acdoctor.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_regresar_menu_doctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listadoDeCitasDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listadoDeCitasDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listadoDeCitasDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listadoDeCitasDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listadoDeCitasDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChequeoRealizado;
    private javax.swing.JTable TablaChequeosDoctor;
    private javax.swing.JButton boton_regresar_menu_doctor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
